---
#title: "Structuring College Access: The Market Segment Model and College Board Geomarkets"
#author: ["Ozan Jaquette (UCLA)", "Karina Salazar (University of Arizona)"]
bibliography: ./../assets/bib/cb_geomarket_bib.bib
csl: ./../assets/bib/apa.csl
format:
  pdf:
    documentclass: article
    #papersize: letter
    number-sections: true
    number-depth: 2
    #toc: FALSE
    #pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
    #keep_tex: true
    extensions: [andrewheiss/wordcount]
editor: visual
geometry:
  margin=1in
fontsize: 11pt
header-includes:
  - \usepackage{setspace}
  - \doublespacing
---

```{r setup, include=FALSE}
library(knitr)
#library(bookdown)

# https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf
library(kableExtra)

#hey ho This many words: {{< words-total >}}
```


# Discussion

The discussion of homophily by @RN4975 describe the logic of The Market Segment model but also an underlying institutional logic of the enrollment management industry. The logic of homophily argues that there is a natural cultural match between students, that colleges should find students who look like students who enrolled at their institution in the past, and that colleges should recruit from the same schools and communities that are popular with peer colleges. We suggest that homophily is the operating logic most consistent with college recruiting behavior observed in the wild. For example, @RN5023 find great overlap in the sets of private schools visited by the University of South Carolina and the University of Alabama. The also find great overlap in the schools visited by Villanova and Notre Dame, with a disproportionate focus on visits to Catholic schools. When we observe that students at selective private colleges tend to be rich and that out-of-state students at public research universities tend to be rich [@RN4722], this is partly because these universities devote most of their recruiting expenditures towards students from affluent schools and communities [@RN4758; @RN5023]. As @RN4975 argues, observed homophily is not the result of voluntary action; rather, homophily is programmed into algorithms that create connections.

The Market Segment Model begins with the status attainment model, that student demand for college is a function of parental education and parental income. @RN4982[chapter 3] demonstrated this argument by showing the correlation between student SAT score-sending behavior and measures of class. The thesis of the Market Segment Model is that that households of particular class and college aspirations are likely to live in particular parts of a metropolitan area and that these geographic territories can be meaningfully captured by Geomarkets. Although Geomarkets appear coarse by contemporary standards, they were a landmark innovation in Geographic segmentation. The Market Segment Model recommends that colleges should identify their core student market segment -- local, in-state, regional, or national -- identify Geomarkets that contain large numbers of households from this market segment, and then target high schools and communities within these Geomarkets. This information is contained in the Market Segment Profile (Appendix A), a standard ouput in EPS software. When considering new Geomarkets to target, colleges should utilize the logic of homophily by identifying Geomarkets that are popular with peer colleges. This information is contained in the Institutional Profile (Appendix A), also included in EPS software.

@RN4982 state that the Market Segment Model merely formalizes the operating logic of college admissions officers. For admissions officers at selective colleges, the logic is that good students from good families are willing to attend good colleges that are far from home. These good families are found in particular parts -- Geomarkets -- of metropolitan areas. By contrast, students from other parts of the metro possess the disposition and achievement to attend their local college. The Market Segment Model formalized this logic and commodified it in EPS software that helped colleges identify desirable Geomarkets and desirable high schools within those Geomarkets. @RN5007 suggest that, once commodified and quantified, the local knowledge of admissions officers becomes redundant. 

Research question 1 investigates racial and socioeconomic variation between and within Geomarkets over time. We find that Geomarkets are highly correlated with race and class. [KARINA SUMMARIZE FINDINGS IN A COUPLE SENTENCES; REVISE PARAGRAPH AS NECESSARY] We show that in 1980, when Geomarkets were being created, that Black people tended to be highly concentrated in the poorest Geomarket in the metropolitan area. Examples include, CA7 -- City of Oakland, MA 6 -- Boston & Cambridge, OH 4 -- City of Cleveland (East), TX17 -- City of Houston (East), TX19 -- City of Dallas, CA21 -- South & South Central Los Angeles, and PA5 -- Philadelphia County. In a handful of metropolitan areas (e.g., Cleveland), Black people remain conentrated in the poorest Geomarkets. In Chicago-Land,  [KARINA -- ONE OR TWO SENTENCES]

These findings are not surprising given the extent of race and class segregation in the US. Furthermore, the correlation between Geomarkets and class is expcted because Geomarket borders were created in service of conceptual model that views demand for higher education as a function of class. @RN4982 is written around New England, with a particular focus on Geomarkets in Connecticut and Massachusetts. @RN4982 do not discuss the intersection of student demand and race. Although unsurprising for early 1980s social science, this silence is conspicuous considering the salience of political controversy surrounding "busing" in Boston and nearby metropolitan areas. 

Research question 2 analyzes the racial and socioeconomic composition of student list purchases. We examine purchases that include all Geomarkets around a metropolitan area in order to assess the potential consequences if including/excluding particular Geomarkets from the purchase. This question is motivated by the @RN4982 recommendation that selective colleges that enroll students from the regional and national market segment should target affluent Geomarkets, while community colleges and non-selective 4-year colleges should focus on middle- and working-class Geomarkets. KARINA -- ADD TEXT SUMMARIZING RESULTS.

This article adds a new perspective to existing explanations about how students are sorted into colleges. The status attainment model argues that college destination is a function of parental education and occupation [@RN1273; @RN1271; @RN1272]. The Market Segment Model is the status attainment model applied to geodemographic market research [CITE]. @RN5033 finds that the educational achievement of Asian American students whose parents are immigrants tend to have high educational achievement even if their parents do not, while the educational achievement of later-generation Asian Americans conforms to status attainment theory. In our analyses of prospects included in student list purchases, Asian American prospects from poor Geomarkets tended to be first-generation students while Asian American prospects from affluent Geomarkets tended to have parents with a BA. Drawing from @RN5033, one explanation for this finding is that Asian students living in low-income Geomarkets tend to have parents who immigrated to the U.S. whereas Asian students living in affluent Geomarkets are more likely to have parents who were born in the U.S.

The cultural capital model explains a process by which upper and upper-middle class families sort themselves into selective colleges by providing their children with the pedigree (academic, extracurricular) valued by selective colleges, information about how to navigate the admissions gauntlet, and social networks that provide an inside track [@RN1228; @RN1241; @RN4991; @RN1814]. This model explains how affluent households maintain a disproportionate enrollment share at selective institutions in an era of holistic admissions ostensibly designed to increase racial and class diversity [@RN4991]. Both the status attainment model and the cultural capital model are demand-side explanations for why education is a "social sieve" [@RN2377; @RN5046] that allows for a modicum of mobility while maintaining a much larger flow of intergenerational class transmission [@RN861]. @RN4722 -- who obtained parental income from federal income tax returns for every U.S. college -- show that the disproportionate enrollment share of high income families at selective private colleges -- and even at most public research universities -- is staggering. These patterns are consistent with the observation by @RN1297[p. 241-242] that educational credentials are property that "support their holders'\ldots claims to monopolize socially and economically advantageous positions."

Supply-side explanations of credentialism and more recent scholarship on enrollment management complement the cultural capital model of sorting students to colleges. The credentialism literature recognizes that colleges have a financial incentive for educational credentials to determine the competition for socially and economically advantageous positions [@RN865; @RN861; @RN880; @RN869] and this credentials arms race favors affluent households. Scholarship on enrollment management describes which students colleges want to enroll and what colleges do to attract these students at different stages of the enrollment funnel [@RN3519; @RN4324; @RN3522; @RN4407; @RN4758; @RN3544; @RN3547; @cottom2017lower]. @RN3519 and @RN4321 describe a tacit arrangement between high school guidance counselors on the demand side and college admissions officers on the supply side. Counselors at well-resourced schools, especially private schools, are motivated to give their students a competitive advantage in admissions. Meanwhile, college admissions officers are motivated to enroll students who can afford full tuition price and are likely to donate in the future. These mutually beneficial desires are consummated by recognzing that upper and upper-middle class applicants satisfy the extracurricular needs of the college. The orchestra needs oboists. The lacrosse team needs players. Quantitative analyses of visits from colleges to high schools are consistent with @RN3519; selective private colleges and public research universities devote most of their recruiting resources on courting students from privileged schools and communities [@RN5023; @RN4758]. However, these analyses conceive of recruiting as something that is done by individual colleges.

Existing explanations of how students are sorted into colleges miss an important supply-side mechanism, third-party vendors that sort students on behalf of colleges. @RN4982 created the Market Segment Model and Geomarkets based on a snapshot of student demand from 1980. @RN4982 argues that demand for higher education is correlated with class, ignoring the historical structural barriers that produced class- and race-based inequality in 1980 student demand. In itself, the Market Segment Model is an unremarkable social science depiction. However, the College Board incscribed Geomarkets and the Market Segment Model into EPS software that told colleges which Geomarkets and high schools to target. Technologies that target target customers based on geography inevitably leverage racial and class segregation [@RN4775; @RN4849; @RN4975]. Furthermore, technologies that use the logic of predictive analytics -- identify correlates in past cases to make predictions for future cases -- are prone to "pernicious feedback loops" [@RN4849]. The structural barriers (e.g., segregation, slavery, Jim Crow) that caused historic place-based inequality in student demand are amplified because EPS recommends that colleges focus recruiting resources on localities that already have high student demand for peer colleges. Geomarkets were subsequently incorporated into the Student Search Service product. We show that that excluding low-income, non-white Geomarkets from student list purchases results in the disproportionate exclusion of first-generation, non-white students with strong test scores. 

## Enrollment Management Industry

The growing salience of third-party vendors warrants a reconfiguration of the organizational field salient to college access. @RN527[p. 148] define organizational fields as, "those organizations that, in the aggregate, constitute a recognized area of institutional life: key suppliers, resource and product consumers, regulatory agencies, and other organizations that produce similar services or products" and that "the virtue of this unit of analysis is that it directs our attention\ldots to the totality of relevant actors." Sociological literatures salient to college access devote substantive attention to schools, colleges, families, and communities.College access scholarship from economics often analyzes the effects of district/state/federal [e.g., @RN5043] policies and the effects of information interventions [@RN4018]. These lines of research do not consider the growing role of third-party vendors, which are increasingly owned by private equity interests and offer software-as-service platforms that perform core functions for schools and colleges.^[ @RN4991 describes the role of independent admissions consultants hired by families as third-party vendors that engage on the demand-side.]

@list_biz describes four key dynamics in the enrollment management (EM) industry, with a focus on the market for student list data. First, EM consulting firms are central to the creation and implementation of recruiting campaigns [@RN5027]. The top two EM consultancies are Ruffalo Noel Levitz, which claims to serve 1,900 colleges annually [@rnlabout_2025], and EAB, which claims to serve 2,100 colleges [@about_eab]. College reliance on EM consultancies is partially explained by the high level of burnout and employee turnover in the EM profession [@hoover_em]. When we issued records requests to public universities about their student list purchases, at least 50\% of universities indicated that they outsourced student list purchases to an EM consultancy. In many cases, the university was buying names each year but no university employee had knowledge about which vendors they were buying from or which search filters they were utilizing.

Second, technological advances creates new means of identifying and serving prospects. College Board began selling the contact information of test-takers in 1972 [@belkin2019-studata]. ACT followed suit and the two testing companies enjoyed a near duopoly for several decades. This business can be described as list-based lead generation based on the direct-mail model. "Free" college search engines (e.g., Cappex, Niche) yielded news sources of student list data. Another data source is college planning software purchased by high school districts and utilized by high school students and guidance counselors. The most widely-known product is Naviance, which claims to be used by more than used by more than 10 million K-12 students and by 40% ofUS high schools [@powerschool]. *Naviance* college planning software feeds into the *Intersect* recruiting platform, which allows colleges to target Naviance users while they are on the platform. *Intersect* is an example of behavioral-based targeting.

The third dynamic in the EM industry has been the growth of test-optional movement, which reduces both the number of paying test-takers and the coverage of student list products sold by College Board and ACT. ACT responded to uncertainty in their core testing business by attempting to become an edtech company [CITE], failing [], and being acquired by Nexus Capital in 2024 [CITE]. Over the last two decades, the testing companies developed new search filters that explicitly incorporated predictive analytics -- for example College Board's Geodemographic Segment filters [CITE] and ACT's predicted probability of enrollment filter [CITE] -- developed free college search engines, and entered the enrollment management consulting market more aggessively. College Board has weathered the test-optional movement thanks to robust revenues from the Advanced Placement product, but the decline in PSAT/SAT/PreACT/ACT test-takers has undermined their oligopoly in the market for student list data.

The fourth dynamic is the transformation from owner-operated to private-equity owned firms and erosion of the distinction between consultancy and software vendor. The 1980s and 1990s was a period of market entry in EM, when college admissions professionals or professors decided to hang up a shingle [@RN5027]. The 2010s were a period of acquisitions and concentration. After regulatory scrutiny pushed private-equity interests out of for-profit college market [@RN5022], private equity investors find value in acquiring firms that provided services to direct providers. Drawing from resource dependence theory, @list_biz describe the proliferation of horizontal acquisitions to grow market share and vertical acquisitions designed to make customers more dependent on particular recruiting products.

EAB exemplifies the the trend towards private equity ownership and industry concentration. EAB is the preeminent EM consultancy, offering software-as-service products along the domains of recruitment, pricing and financial aid, student success, and advancement [@about_eab]. The origins of EAB trace to Bill Royall, who founded Royall & Company in 1983 to provide direct marketing and fundraising for Republican political campaigns [@jump_2020]. Royall did not sign its first colege client for several years, but EM became the primary focus by 1995. Royall was acquired by the health tech firm Advisory Board Company for \$850 million in 2015 and then by Vista Equity Partners for \$1.5 billion in 2017, renaming it EAB [@drew_hansen_2017]. 

As an owner-operated consultancy, Royall was the market leader in purchasing student lists from student list vendors on behalf of clients. Under Vista, EAB entered the market for student list data by completing a series of acquisitions that targeted the "leads" and "inquiries" stages of the enrollment funnel. In 2019, EAB acquired YouVisit, a leading provider of virtual tours. YouVisit is an engine for "inquiries" in that taking a virtual tour shows interest in a college and leaves a trail of contact information for subsequent recruiting interventions. In 2020, EAB acquired Cappex, a leading free college search engine, which is an engine for leads in that students provide contact details and other information. In 2021, EAB and PowerSchool -- the leading provider of K12 student information systems and a subsidiary of Vista -- jointly acquired the EM consultancy/software vendor Hobsons. EAB acquired Hobson's student success software, Starfish, while PowerSchool acquired Hobson's Naviance product and its sister recruiting product Intersect. EAB paid PowerSchool to become the exlusive reseller of Intersect. Finally, in 2022, EAB acquired Concourse, the leading "direct admissions" platform. EAB combined these acquisitions into create [Enroll360](https://eab.com/solutions/enroll360/):

> We spent the last couple of years creating a connected recruitment ecosystem that allows enrollment leaders to keep pace with students pursuing increasingly digital journeys to college. This work led us to join forces with several leading companies: Cappex, Intersect, Wisr, and YouVisit\ldots Individually, each solution can solve important challenges at various stages of the enrollment funnel\ldots By bringing these capabilities together, our vision is to reinvent how enrollment leaders reach their goals [@koppenheffer_2021]

Enroll360 exemplifies a new kind of student list product that leverages proprietary data to sell software. Historically, College Board and ACT sold prospect contact information at a price-per-prospect (e.g., \$0.50). The goal was to generate revenue from the sale of names. By contrast, Enroll360 wraps several proprietary databases of names (e.g., Cappex, Intersect) into a software-as-service platform that recruits those prospects at different stages of the enrollment funnel. Here, the goal of lists is to create demand for software, which is more expensive than names. Colleges that are interested in recruiting these prospects must buy an Enroll360 subscription. Like College Board *Student Search Service* contemporary software-as-service recruiting products incorporate search filters that enable colleges to choose which prospects they recruit. For example, reporting @markup_naviance shows how the Intersect recruiting platform allows colleges to send paid advertisements to Naviance users. Intersect customers (colleges) control which Naviance users will receive recruiting messages by filtering on filters such as "academic ability," intended majors, and wheather students used Naviance to "research competitor institutions" [@markup_naviance]. A procurement document from the University of Utah explains that the Intersect subscription is necessary to recruit the proprietary database of Naviance users: [@utah_procurement]:

> The marketing services being purchased operates within the PowerSchool Naviance platform, which is a proprietary system, that no other company has access to. There is unique group of prospective students who are only in the PowerSchool Naviance platform. We have spoken with several vendors where we can reach out to prospective students. Each vendor has their own proprietary website or database where select students can be reached.

An under-studied and under-regulated third-party EM industry has negative consequences for colleges and for students. Accross multiple student list products, we see a growing number of filters that recommend which prospects to target based on the beheavior of previous cohorts of students. The ACT/Encoura "Enrollment Predictor" filter enables colleges to filter prospects based on the predicted probability of enrollment, which is created based on analyzing the enrollment decisions of previous cohorts of students [@schmidt_2019]. College Board Geodemographic Segment filters categorizes each Census Tract into one of about two dozen clusters based on the college-going behavior of previous cohorts [@RN4565] and is based on the Claritas/PRIZM market segmentation system that categorized zip codes into groups useful for merchants [@RN4957]. An investor-facing @vista_eab_ml video promoting EAB's "Pipeline Analytics" product states, "we are using artificial intelligence and machine learning to help schools build list of students that may be more more likely to enroll and persist in their university." The product "identifies students that would be a good match for a school based on their similarity to students who have succeeded there before and then provides them [the students] information about those institutions so that they choose to apply and ultimately enroll." Each of these products are based on the underlying logic of correlations and homophily discussed by @RN4975 and applied by @RN4982. These products identify correlations in a historic snapshot of students and apply those relationships to make recommendations about which prospects to target in the present. As such, all of these technologies amplify the effect of previous inequality in student demand, which is itself a consequence of structural inequality in educational opportunity.

Market dynamics in the EM industry raise policy concerns about tuition prices, student choice, and competition in the market for EM consultancies
may also affect competition, prices, and student choice. To the extent that colleges must buy expensive software to recruit prospects contained in an associated database, this expenditure will ultimately be passed on to students in the form of higher prices or reduced expenditure on education. Unfettered horizontal and vertical acquisitions in the EM industry causes the EM industry to become more concentrated. Smaller consultancies that do not control veritial inputs may be unable to compete with companies that have acquired proprietary pools of prospects. Fewer EM consultancies means less competition and higher consulting fees, which will be passed on to consumers. Finally, the blurring of the lines between consultancy and student list vendor suggests that large consultancies will funnel prospects only to those colleges that are willing and able to pay for subscriptions, which raises policy concerns about student choice.

## Developing a Knowledge Infrastructure

Regulation of the higher education industry should be informed by research that investigates the "totality of relevant actors" [@RN527, p. 148] in the organizational field. Unfortunatel, scholarship salient to education policy and regulation have ignored two, related economic transformations. First, third-party vendors offer software platforms that perform core tasks of organizations, including schools and colleges [@list_biz]. Second, private firms comprise a growing share of economic activity [@RN5037; @RN5038]. Most firms in EM and the broader edtech sector are private. However, private firms face fewer disclosure requirements than publicly traded firms. The paucity of research about third-party vendors that structure college access is substantially due to difficulty obtaining data for empirical analyses. The research community must figure out how to systematically investigate the role of private firms and investors in education, so that we can hold private interests accountable for education policy goals.

Knowledge infrastructures are "systems of observation and measurement" [@RN5025, p. 743] that provide the foundation for scalable research. They collect, process, and distribute data in ways that "enable certain kinds of knowledge production while simultaneously channeling researchers away from questions not readily answerable within\ldots that infrastructure" [@RN5025, p. 742]. The knowledge infrastructure of education research largely consists of data about students, schools, and colleges. It has been shaped by the ascendance of economics [@RN5036], which incorporates district, state, and federal administrative data to evaluate the effects of schools and policies on student outcomes [@RN5043]. The research community mobilized to investigate for-profit colleges because for-profit colleges and students were included in ongoing data collection [@RN5022]. By contrast, researchers ignored the growth of private, for-profit, third-party vendors (e.g., PowerSchool, Parchment) because these organizations are excluded from data collections known to education researchers.

We argue that sociologists and adjacent scholars should expand the domain of the education research knowledge infrastructure to include third-party vendors in enrollment management, and edtech more broadly. This is a difficult task. Student unit record data owned by district, state, and federal agencies is simultaneously granular -- can evaluate a particular policy -- and macro -- can speak to broad trends in the education sector. By contrast, obtaining granular data about third-party products in education is difficult because these data are owned by private interests that do not want researchers to interrogate their products [@RN4774; @RN4842]. We see two broad avenues for research: case studies involving primary data collection -- including this study -- which tend to have a granular focus on particular products or vendors; and secondary data analysis, which may have a more macro focus. 

Although case study research often relies on interview and ethnographic data, another approach to data collection is to issue records requests to public entities that contract with third-party entities. For example, @RN5039 analyze public university contracts with online program managers (OPMs). The present manuscript is an example of case study research. We issued public records requests to obtain tabular data about student list purchases. However, this process was labor intensive, requiring the pro bono efforts of several law firms. Public records requests seem better suited to obtaining contracts. Qualitative or computational text analysis of publicly available websites and social media provides another avenue for data collection. Here, data collection is efficient but data processing is often labor intensive. Like investigative reporting [@markup_naviance], case study research can produce granular analyses of particular products (e.g., Intersect, Enroll360) that yield insight into the underlying mechanisms of how third-party vendors structure college access. However, data collected for case study research typically does not meet the knowledge infrastructure standard of repeated, ongoing data collection that can be the foundation for scalable research. 

We see subscription databases about private markets as having the potential to create a knowledge infrastructure for scalable research on the role of private firms and private equity funders in education, and also their role in other domains of interest to sociology. A growing set of "market intelligence" data providers serve the information needs of the investment community by providing data on private firms and deals involving private firms. These databases tend to include three broad "types" of data: (1) *firm-level data* (e.g., location, employees, financials); (2) *acquisitions*, encompassing who acquired whom and resulting ownership structure); and (3) *investments*, which include amounts/valuations/stake percentages of private equity investments. Some providers provide all three types of data (e.g., [*S&P Capital IQ*](https://www.spglobal.com/market-intelligence/en), [*LSEG Workspace*](https://www.lseg.com/en)). Other providers specialize. For example, [*PitchBook*](https://pitchbook.com/) is a leading provider of data about investments in private companies by private equity firms, while [*Orbis*](https://login.bvdinfo.com/R1/Orbis) is a leading provider of firm-level data for non-U.S. private firms. These databases are often utilized in journals of finance or management that consider private equity markets or patterns of acquisitions [e.g., @RN5044; @RN5038]. Interestingly, the database subscriptions operate similar to contemporary student list products; an interactive, user-facing platform is wrapped around several sources of proprietary data. University libraries provides full or partial access to some subscriptions, while others must be purchased. 

Although scholars cannot share subscription data, they can share code to process and analyze these data. We recommend that scholars develop panel datasets examining change over time in the firms operating in particular industries and acquisitions and private equity investments in those industries. For example, empirical scholarship can examine change over time in concentration in the enrolment management industry and its transformation from an owner-operated to a largely private-equity owned industry. Subsequent analyses could investigate the portfolio of large owners, their ties to other industries -- such as the direct-provider for-profit college market -- and the vertical inputs/technologies they are investing in.

# References

::: {#refs}
:::

