<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ozan Jaquette (UCLA)">
<meta name="author" content="Karina Salazar (University of Arizona)">

<title>Structuring College Access: The Market Segment Model and College Board Geo-markets</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="front_end_files/libs/clipboard/clipboard.min.js"></script>
<script src="front_end_files/libs/quarto-html/quarto.js"></script>
<script src="front_end_files/libs/quarto-html/popper.min.js"></script>
<script src="front_end_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="front_end_files/libs/quarto-html/anchor.min.js"></script>
<link href="front_end_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="front_end_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="front_end_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="front_end_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="front_end_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="front_end_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="front_end_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head><body class="fullcontent">\usepackage{setspace}
\doublespacing






<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Structuring College Access: The Market Segment Model and College Board Geo-markets</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Ozan Jaquette (UCLA) </p>
             <p>Karina Salazar (University of Arizona) </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In 1983, Zemsky and Oedel authored <em>The Structure of College Choice</em>, published by <em>The College Board.</em> This book develops the Market Segment Model and introduces local “community-based enrollment markets” (p.14) – later called “geomarkets” – which are the basis for the College Board market Enrollment Planning Service (EPS), a market research product. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>, pp., 9-10)</span> write that the Market Segment Model sought to quantify the knowledge that college admissions officers have about student demand:</p>
<blockquote class="blockquote">
<p>Admissions officers invariably are tellers of stories – about the colleges they represent, about the colleges they attended, about each other, and about the often vagabond life of college recruitingWe believe that the institutions of admissions officers actually comprise a remarkably systematic body of knowledge about the college selection processOur research, thus, is based on listening carefully to what admissions officers have to say.”</p>
</blockquote>
<p><span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 10</a>)</span> stress the importance of “knowing the territory”:</p>
<blockquote class="blockquote">
<p>A good recruiter knows where to look for prospective applicants, as seen in the students’ willingness or eluctance to travel. It is necessary to identify not only the most promising communities or poools, but also the specific neighborhoods within those communities – hence the recruiter’s emphasis on feeder high schools. From the beginning, we have sought to mold our research to these concepts, to capture and quantify the phenomenon behind the folklore. Thus, it is the admissions officers’ notion of admissions pools that dictates the geographic units of our analysis.” [p.&nbsp;11]</p>
</blockquote>
<p>The Market Segment Model was created by analyzing College Board data about which colleges SAT test-takers from 1980 sent scores to. High school students who sent scores mostly to colleges in their local geomarket were defined as “local” students. “In-state” students were those who sent most scores to colleges outside their local market but in their home state. “Regional” students were those who sent most scores to colleges outside their home state but in their region (e.g., New England, Midwest). “National” students were those who sent most scores to colleges outside their region. Having categorized students, each local geomarket could be evaluated by the number of students from each of the four market segments, yielding the Market Segment Profile (see <a href="#tbl-market-segment-characteristics" class="quarto-xref">Table&nbsp;1</a>). Next, for each local geomarket, the Institutional Profile (see <a href="#tbl-sample-institutional-profile" class="quarto-xref">Table&nbsp;2</a>) the number of students from each market segment that sent scores to a particular college, which could be your college or a competitor.</p>
<p>Collectively, the quantitative outputs of the Market Segment Model provided intelligence about where are the desirable students and which students might consider your college or a competitor. The Market Segment model and geomarkets became the basis or the College Board Enrollment Planning Service (EPS), founded in 1984 and still active today. <span class="citation" data-cites="RN5019_2010">College Board (<a href="#ref-RN5019_2010" role="doc-biblioref">2010</a>)</span> says “Enrollment Planning Service (EPS) the analysis tool that pinpoints the schools and geomarkets where your best prospects are most likely to be found.” <span class="citation" data-cites="RN5021">Noel-Levitz (<a href="#ref-RN5021" role="doc-biblioref">1998</a>)</span> reports that in 1995, 37% of 4-year publics and 49% of 4-year privates used EPS, while 41% of 4-year publics and 16% of 4-year privates used ACT’s market analysis service product, which was similar to EPS.</p>
<p>In 19XX, geomarkets were incorporated into the College Board Student Search Service student list product, which College Board created in 1972 <span class="citation" data-cites="belkin2019-studata">(<a href="#ref-belkin2019-studata" role="doc-biblioref">Belkin, 2019</a>)</span>. Student lists contain the contact information of prospective students, the basic input for recruiting campaigns that target individual prospects using mail, email, and targeted social media. RN4895 reported that 87% of private and 86% of public four-year institutions purchase student lists. The Student Search Service database consists of College Board test-takers. Colleges pay a fee for each prospect (e.g., $0.50 in 20XX) and control which prospect profiles through purchase by selecting search filters, such as high school graduation year, SAT score, AP test score, state, etc. Geomarket filters enable colleges to include/exclude prospects from particular geomarkets.</p>
<p>Scholarship in the sociology of education describes schools and colleges as “sorting machines” that reproduce inequality by incorporating, creating, and allocating students to different categories <span class="citation" data-cites="RN4873">(<a href="#ref-RN4873" role="doc-biblioref">Domina, Penner, &amp; Penner, 2017</a>)</span>. Given the consequences subsequent outcomes, the sociology of education is particularly concerned with the transition from high school to college. Over the last decade or so, scholarship on college access has begun to take more seriously the idea that colleges are not passive recipients of applications; rather they expend substantial resources soliciting demand from desirable applicants <span class="citation" data-cites="RN3519 RN4774 RN4324">(<a href="#ref-RN4774" role="doc-biblioref">Cottom, 2020</a>; <a href="#ref-RN4324" role="doc-biblioref">Holland, 2019</a>; <a href="#ref-RN3519" role="doc-biblioref">Stevens, 2007</a>)</span>. Most scholarship on recruiting analyzes the behavior of individual colleges, thereby assuming that recruiting behavior is a function of individual colleges <span class="citation" data-cites="RN4758 RN4759">(<a href="#ref-RN4759" role="doc-biblioref">Salazar, 2022</a>; e.g., <a href="#ref-RN4758" role="doc-biblioref">Salazar, Jaquette, &amp; Han, 2021</a>)</span>. <span class="citation" data-cites="RN5012">Jaquette &amp; Salazar (<a href="#ref-RN5012" role="doc-biblioref">2024</a>)</span> analyze the College Board <em>Student Search Service</em> product, highlighting the role that third-party products play in structuring the recruiting behavior of colleges. The authors show that the utilization of particular search filters – particularly geographic filters, such as zip code – is associated with systematic racial exclusion that does not depend on which college purchased the list.</p>
<p>However, prior research has not examined the role of third-party market research in reproducing socioeconomic and racial inequality. This manuscript analyzes the Market Segment Model and College Board Geomarkets as a case study of quantification. We develop arguments from the broader literature on quantification [e.g.,] <span class="citation" data-cites="RN5003 RN5005 RN5007">(<a href="#ref-RN5003" role="doc-biblioref">Espeland &amp; Sauder, 2016</a>; <a href="#ref-RN5007" role="doc-biblioref">Espeland &amp; Stephens, 2008</a>; <a href="#ref-RN5005" role="doc-biblioref">McArthur &amp; Reeves, 2022</a>)</span>, particularly the discussions of correlation and homophily from <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021</a>)</span>. Predictive analytics are based on correlation. When we use data on past correlations to make recommendations about the future, we amplify the effects of historic structural inequality. The Market Segment Model analyzes SAT score-sending data from 1980 and concludes that student demand for higher education is primarily a function of social class= <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983</a>)</span>. Homophily is the idea that actors that share common characteristics are likely to form connections with one another. The Market Segment Model argues that homophily is the organizing principle of student demand and competition between colleges, that “the hierarchical structure of collegiate competition largely reflects the stratified social and economic dimensions of the communities from which colleges draw their students” <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983, p. 72</a>)</span>. Subsequently, the assumption of homophily is programmed into the EPS and Student Service Service products that colleges utilize to decide where to focus recruiting energy.</p>
<p>Empirically, our analyses address the following research questions, which speak to how geomarkets are utilized within the Enrollment Planning Service and within the Student Search Service student list product. First, what is the socioeconomic and racial variation between geomarkets in metropolitan areas and how does this variation change over time? We address this question by spatially joining the geomarket shapefile to Census data about socioeconomic and racial characteristics. Second, how does the socioeconomic and racial composition of included versus included prospects vary when student list purchases filter on particular geomarkets, in concert with other commonly used search filters? We address this question by analyzing student list purchases that do not filter geomarkets and simulating which prospects would have been included had they filtered on particular geomarkets. We obtained these data by issuing public records requests to public universities in four states. Third, in student list purchases that filtered on geomarkets, how does the socioeconomic and racial composition of included students compare the that of the geomarket and how does it compare to that of the broader metropolitan area?</p>
<p>Scholarship on quantification in education has focused on consumer-facing measures such as U.S. News Rankings <span class="citation" data-cites="RN5003">(<a href="#ref-RN5003" role="doc-biblioref">Espeland &amp; Sauder, 2016</a>)</span> and UK “league tables” about school quality <span class="citation" data-cites="RN5005">(<a href="#ref-RN5005" role="doc-biblioref">McArthur &amp; Reeves, 2022</a>)</span>. To our knowledge, prior knowledge has not examined business-facing measures produced by third-party market research. Here, the desirable attributes of students and places they live are quantified with the purpose of informing colleges about where they should allocate recruiting resources to efficiently enroll the most desirable students. We reason that market research reproduces inequality by encouraging colleges to plan their recruiting efforts based on a snapshot of social stratification in student demand that is substantially a function of historic, structural inequality in educational opportunity. In contrast to <span class="citation" data-cites="RN5005">McArthur &amp; Reeves (<a href="#ref-RN5005" role="doc-biblioref">2022</a>)</span>, we cannot demonstrate the effect of geomarkets on inequality. However, we show the mechanisms of how geomarkets reproduce inequality by simulating who is included/excluded when geomarkets are utilized within student list purchases as recommended by <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span>.</p>
<p>In the following section we provide background information about enrollment management and scholarship on recruiting. Second, we introduce core ideas and concepts from scholarship on quantification. Third, we apply these ideas to a close read of <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> and motivate hypotheses. Four, we describe data and methods. Fifth, we present results. Finally, we discuss implications for scholarship, policy, and practice.</p>
</section>
<section id="background-enrollment-management" class="level1">
<h1>Background: Enrollment Management</h1>
<p>The term “enrollment management” (EM) refers to a profession, an administrative structure, and an industry. As a profession, EM integrates techniques from marketing and economics in order to “influence the characteristics and the size of enrolled student bodies” <span class="citation" data-cites="RN2771">(<a href="#ref-RN2771" role="doc-biblioref">Hossler &amp; Bean, 1990, p. xiv</a>)</span>. As an administrative structure, the EM office typically controls the activities of admissions, financial aid, and recruiting <span class="citation" data-cites="RN2406">(<a href="#ref-RN2406" role="doc-biblioref">Kraatz, Ventresca, &amp; Deng, 2010</a>)</span>. The EM industry consists of university personnel (e.g., admissions counselors, VP for enrollment management), professional associations (e.g., National Association for College Admission Counseling), and third-party servicers that produce market research, software, and and consulting services (e.g., College Board, ACT, EAB, Huron, Slate, PowerSchool).</p>
<p>Figure <a href="#fig-em-funnel" class="quarto-xref">Figure&nbsp;1</a> depicts the “enrollment funnel,” which modifies the traditional “marketing funnel” to depict broad stages in the process of recruiting students <span class="citation" data-cites="RN4986 RN2004">(<a href="#ref-RN2004" role="doc-biblioref">EAB, 2019</a>; <a href="#ref-RN4986" role="doc-biblioref">Litten, Sullivan, &amp; Brodigan, 1983</a>)</span>. The funnel begins with a large pool of “prospects” (i.e., prospective students) that the university would like to enroll. “Leads” are prospects whose contact information has been obtained. “Inquiries” are prospects that contact the institution and consist of two types: first, inquiries who respond to an initial solicitation (e.g., email) from the university; and second, “student-as-first-contact” inquiries who reach out to the university on their own (e.g., sending ACT scores). <!--  Applicants consist of inquiries who apply plus "stealth applicants" who do not contact the university before applying.  -->The funnel narrows at each successive stage in order to convey the assumption of “melt” (e.g., a subset of “inquiries” will apply). Practically, the purpose of the enrollment funnel is to inform recruiting interventions that target one or more stages. These interventions seek to increase the probability of “conversion” across stages <span class="citation" data-cites="RN4322">(<a href="#ref-RN4322" role="doc-biblioref">Campbell, 2017</a>)</span>. At the top of the enrollment funnel, purchasing student lists is the primary means of converting prospects to leads <span class="citation" data-cites="list_biz">(<a href="#ref-list_biz" role="doc-biblioref">Jaquette, Salazar, &amp; Martin, 2022</a>)</span>. Purchased leads are served emails, brochures, and targeted social media advertisements designed to solicit inquiries and applications <span class="citation" data-cites="RN4895">(<a href="#ref-RN4895" role="doc-biblioref">Ruffalo Noel-Levitz, 2022</a>)</span>.</p>
<p>Scholarship at the nexus of enrollment management and college access can be categorized by which part(s) of the enrollment funnel they focus on. The majority of scholarship focuses on the admissions stage, analyzing which admissions criteria are utilized and/or which applicants are admitted <span class="citation" data-cites="RN4874 RN4993 RN4131 RN3522 poon2022rethinking">(e.g., <a href="#ref-RN4874" role="doc-biblioref">Hirschman, Berrey, &amp; Rose-Greenland, 2016</a>; <a href="#ref-RN3522" role="doc-biblioref">Killgore, 2009</a>; <a href="#ref-poon2022rethinking" role="doc-biblioref">O. Y. A. Poon &amp; Bastedo, 2022</a>; <a href="#ref-RN4131" role="doc-biblioref">Posselt, 2016</a>; <a href="#ref-RN4993" role="doc-biblioref">Taylor, Rosinger, &amp; Ford, 2024</a>)</span>. A growing literature analyzes the earlier “recruiting” stages of identifying leads, soliciting inquiries, and soliciting applications. Scholarship on recruiting has conceptualized recruiting behavior as an indicator of college enrollment priorities <span class="citation" data-cites="RN4758">(<a href="#ref-RN4758" role="doc-biblioref">Salazar et al., 2021</a>)</span> and identifies recruiting practices as a mechanism for social reproduction in college access <span class="citation" data-cites="RN4324 RN3519">(<a href="#ref-RN4324" role="doc-biblioref">Holland, 2019</a>; <a href="#ref-RN3519" role="doc-biblioref">Stevens, 2007</a>)</span>.</p>
<p>Ethnographies by <span class="citation" data-cites="RN3519">Stevens (<a href="#ref-RN3519" role="doc-biblioref">2007</a>)</span> and by <span class="citation" data-cites="RN4407">Khan (<a href="#ref-RN4407" role="doc-biblioref">2011</a>)</span> analyze the connections between privileged colleges and privileged high schools. <span class="citation" data-cites="RN4407">Khan (<a href="#ref-RN4407" role="doc-biblioref">2011</a>)</span> shows how guidance counselors at elite private school guidance counselors lobby admissions counselors on behalf of marginal students. <span class="citation" data-cites="RN3519">Stevens (<a href="#ref-RN3519" role="doc-biblioref">2007</a>)</span> finds that college admissions officers visit high schools as a means of maintaining positive relationships with guidance counselors at affluent feeder schools. Consistent with this finding, quantitative case studies of off-campus recruiting visits show that selective private colleges visit affluent, predominantly white schools and communities, with a disproportionate number of visits to private high schools <span class="citation" data-cites="RN5014 RN4330">(<a href="#ref-RN5014" role="doc-biblioref">Jaquette, Han, &amp; Castañeda, 2024</a>; <a href="#ref-RN4330" role="doc-biblioref">Jaquette &amp; Salazar, 2018</a>)</span>. Additionally, public research universities often make make more out-of-state recruiting visits than in-state visits, and these out-of-state visits focus on the same set sorts of schools targeted by selective private universities <span class="citation" data-cites="RN4759 RN4758">(<a href="#ref-RN4759" role="doc-biblioref">Salazar, 2022</a>; <a href="#ref-RN4758" role="doc-biblioref">Salazar et al., 2021</a>)</span>.</p>
<p>Other studies investigate recruiting behavior by non-selective institutions <span class="citation" data-cites="RN4520 cottom2017lower dache2018dangling">(<a href="#ref-cottom2017lower" role="doc-biblioref">Cottom, 2017</a>; <a href="#ref-dache2018dangling" role="doc-biblioref">Dache-Gerbino, Kiyama, &amp; Sapp, 2018</a>; <a href="#ref-RN4520" role="doc-biblioref">Posecznick, 2017</a>)</span>. Analyzing recruiting from the perspective of high school students, <span class="citation" data-cites="RN4324">Holland (<a href="#ref-RN4324" role="doc-biblioref">2019</a>)</span> finds that underrepresented students were drawn to colleges that made them feel wanted, often attending institutions with lower graduation rates and requiring larger loans than other college options. <span class="citation" data-cites="cottom2017lower">Cottom (<a href="#ref-cottom2017lower" role="doc-biblioref">2017</a>)</span> shows that for-profit colleges found a niche in Black and Latinx communities because traditional colleges ignored these communities. <!--  WHAT YOU SAID ABOUT POSECZNICK Posecznick (2017) studied the “Ravenwood College,” a private nonprofit college founded to serve working Black women. Consistent with analyses of tuition discounting by Lapovsky (2001), the survival of Ravenwood depends on the success of admissions officers in identifying prospects (e.g., through on- and off-campus recruiting events) and “converting” these prospects to enrolled students.  --></p>
<p>We make two observations about the recruiting literature. First, consistent with scholarship on political economy <span class="citation" data-cites="RN4517 cottom2017lower RN5015">(<a href="#ref-cottom2017lower" role="doc-biblioref">Cottom, 2017</a>; <a href="#ref-RN5015" role="doc-biblioref">Marion Fourcade &amp; Healy, 2024</a>; <a href="#ref-RN4517" role="doc-biblioref">Stevens &amp; Gebre-Medhin, 2016</a>)</span> and industrial organization <span class="citation" data-cites="RN1549 RN2133">(<a href="#ref-RN2133" role="doc-biblioref">Hoxby, 1997</a>; <a href="#ref-RN1549" role="doc-biblioref">Winston, 1999</a>)</span>, the industry is characterized by a vertical hierarchy of postsecondary institutions matching to a vertical hierarchy of customer niches, a process that exemplifies the idea that higher education is mechanism of social reproduction <span class="citation" data-cites="RN2377 RN4873">(<a href="#ref-RN4873" role="doc-biblioref">Domina et al., 2017</a>; <a href="#ref-RN2377" role="doc-biblioref">Stevens, Armstrong, &amp; Arum, 2008</a>)</span>.<!--  For example, for-profit institutions target adults in communities not being targeted by traditional colleges [@cottom2017lower]. Non-selective private non-profits target prospects who might be considering community college or a local state colleges [@RN4324]. Selective private colleges target private high schools, with a particular link between sectarian high schools and colleges of the same faith [@RN5014], but these schools are increasingly targeted by out-of-state public research universities, suggesting growing competition for a coveted market niche. --> Second, by focusing on the behaviors of individual colleges, the literature implicitly states that recruiting is something done by individual colleges. <!--  
Why then, does recruiting behavior look so similar across colleges of a particular "type"?[^1]
[^1]: New institutional theory offers one explanation [@RN527]. In highly developed organizational fields like higher education, forces of competitive and institutional isomorphism -- including institutional locics -- compel organizations adopt similar practices as their peers. Practices deemed advantageous spread quickly, for example, public research universities targeting nonresident prospects to compensate for declines in state appropriations. These behaviors are conceived as autonomous decisions by individual colleges, albeit structured by institutional logics.
 --></p>
<!-- make or buy  
The process of recruiting students involves many "make or buy" decisions about whether to perform a given task in-house or outsource it to a third-party vendor. EM consulting firms provide advice and implementation in the areas of marketing, recruiting, pricing and financial aid, and student success. As "creating a class" has becomes complicated and high-stakes [@RN3519], many colleges hire EM consulting firms to develop and/or implement recruiting campaigns. The two largest enrollment consulting firms -- Ruffalo Noel Levitz and EAB -- claim to serve more than 3,000 colleges and universities collectively [@rnlabout; @eabcomm]. In our data collection, attempting to obtain data about student list purchases from all public universities in four states, at least half of these universities outsourced student list purchases to an EM consultancy [@list_biz; @list_empirics].
-->
<p>However, the recruiting behavior of colleges is structured by third-party actors. Drawing from scholarship on organizational theory <span class="citation" data-cites="RN4738">(<a href="#ref-RN4738" role="doc-biblioref">Scott &amp; Davis, 2007</a>)</span>, enrollment management processes involve many “make or buy” decisions about whether to perform a given task in-house or outsource it to a third-party vendor <span class="citation" data-cites="list_biz">(<a href="#ref-list_biz" role="doc-biblioref">Jaquette et al., 2022</a>)</span>. EM consulting firms provide advice and implementation in the areas of marketing, recruiting, pricing and financial aid, and student success. <!-- As "creating a class" has becomes complicated and high-stakes [@RN3519], many colleges hire EM consulting firms to develop and/or implement recruiting campaigns. --> The two largest enrollment consulting firms – Ruffalo Noel Levitz and EAB – claim to serve more than 3,000 colleges and universities collectively <span class="citation" data-cites="rnlabout eabcomm">(<a href="#ref-eabcomm" role="doc-biblioref">EAB, n.d.</a>; <a href="#ref-rnlabout" role="doc-biblioref">Ruffalo Noel Levitz, 2023</a>)</span>.</p>
<p>Moreover, process of college access is structured by third-party recruiting products utilized by colleges. <span class="citation" data-cites="RN5012">Jaquette &amp; Salazar (<a href="#ref-RN5012" role="doc-biblioref">2024</a>)</span> deconstruct the College Board <em>Student Search Service</em> product. Selection devices are procedures or routines for making categorical decisions based on input values <span class="citation" data-cites="RN4778">(<a href="#ref-RN4778" role="doc-biblioref">Hirschman &amp; Bosk, 2020</a>)</span>. Student list products are selection devices that enable colleges to choose which prospective students they target or ignore based on search filters that incorporate search filters (e.g., high school graduating class, state) which enable colleges to select prospective students. “Racialized inputs” are ostensibly race-neutral inputs that are systematically correlated with race because marginalized racial/ethnic groups have historically been excluded from the input <span class="citation" data-cites="RN4786">(<a href="#ref-RN4786" role="doc-biblioref">Norris, 2021</a>)</span>. <span class="citation" data-cites="RN5012">Jaquette &amp; Salazar (<a href="#ref-RN5012" role="doc-biblioref">2024</a>)</span> argue that several frequently utilized student list filters (zip code, AP test score, SAT score) are racialized inputs. Using a national sample of high school students, and also using data from actual student lists purchased by public universities, they show that racialized search filters have a strong negative relationship with the selection of Black and Latinx prospects. <!-- Using data from actual student lists purchased by public universities, they show that raciaized search filters -- used in conjunction with other search filters -- yield dramatic racial inequality in which prospective students are targeted. --></p>
<p>Student list products offer many geographic filters. Geographic borders are perhaps the most commonly studied racialized input in scholarship about algorithmic bias <span class="citation" data-cites="RN4775 RN4849 RN4887">(<a href="#ref-RN4775" role="doc-biblioref">Benjamin, 2019</a>; <a href="#ref-RN4887" role="doc-biblioref">Harcourt, 2007</a>; <a href="#ref-RN4849" role="doc-biblioref">O’Neil, 2016</a>)</span>, owing to extreme racial segregation in the U.S. In addition to offering geographic filters based on known geographic borders (e.g., zip code, county, CBSA, state), the College Board created new geographic borders that subsequently became filters in the <em>Student Search Service</em>. The geodemographic segment filters utilize cluster analysis to allocate each census tract and each high school into different categories based past college enrollment and other factors <span class="citation" data-cites="RN4565">(<a href="#ref-RN4565" role="doc-biblioref">College Board, 2011</a>)</span>. Geodemographic search filters can be read as the mimicry of corporate market logic <span class="citation" data-cites="RN4004">(<a href="#ref-RN4004" role="doc-biblioref">Thornton, 2002</a>)</span> in that they apply the logic and methods of commercial geodemographic market segmentation products, such as PRIZM by the Claritas Corporation <span class="citation" data-cites="RN4957">(<a href="#ref-RN4957" role="doc-biblioref">McKelvey, 2022</a>)</span>, to the case of college recruiting.</p>
<p>Geomarket search filters, the focus of this manuscript, slice states and metropolitan areas into smaller, local recruiting markets. For example, geomarket “CA08” refers to “Alameda Country excluding Oakland.” A university might purchase prospect contact information by filtering on this geographic region in combination with additional filters, such as year of high school graduation and SAT test score. When we initiated this manuscript, we asked ourselves, “where did geomarket filters come from?” The answer surprised us. We had imagined ourselves studying the application of the “data science revolution” to college recruiting, but it turned out we were studying the 1970s and 1980s! The Market Segment Model and geomarkets can be read as the application of social science research methods to “capture and quantify the phenomenon behind the folklore” <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983, p. 11</a>)</span> of college admissions officers. This work, comissioned by College Board, was subsequently turned into a market research tool – The College Board Enrollment Planning Service – that helps colleges decide where to look for prospective students.</p>
<!--The enrollment management industry emphasizes market research.
Market research is the process of producing information that informs decisions about product design or how to find customers.   -->
<p>The enrollment management industry puts great stock in market research. <span class="citation" data-cites="RN4986">Litten et al. (<a href="#ref-RN4986" role="doc-biblioref">1983, p. 17</a>)</span> define market research as all “activities intended to increase understanding of a market and consumer behavior in that market.” At the most basic level, in-house market research is a function of being intentional about record-keeping and using those records <span class="citation" data-cites="RN3519">(<a href="#ref-RN3519" role="doc-biblioref">Stevens, 2007</a>)</span>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> However, most market research in the contemporary enrollment management industry is produced by third-party organizations. For example, Ruffalo-Noel Levitz and EAB both produce prodigious amounts of market research, some publicly available as a means of business development [e.g., <span class="citation" data-cites="RN4741">Ruffalo Noel Levitz (<a href="#ref-RN4741" role="doc-biblioref">2020</a>)</span>; <span class="citation" data-cites="RN4728">EAB (<a href="#ref-RN4728" role="doc-biblioref">2018</a>)</span>, but most only available to clients. EPS remains the market research arm of College Board, while Encoura Eduventures is the market research arm of ACT.</p>
<p>Despite being central to enrollment management for at least 40 years <span class="citation" data-cites="RN4986">(<a href="#ref-RN4986" role="doc-biblioref">Litten et al., 1983</a>)</span>, the role of third-party market research has been ignored by scholarship on college access. Scholarship on college access often takes a demand-side perspective, whereby household differences in economic and cultural capital yield stratification in student preferences and the ability to gain admission <span class="citation" data-cites="RN4935 RN1814">(e.g., <a href="#ref-RN4935" role="doc-biblioref">Chetty, Deming, &amp; Friedman, 2023</a>; <a href="#ref-RN1814" role="doc-biblioref">McDonough, 1997</a>)</span>. However, market research informs where colleges look for students and which prospective students to target. These recruiting interventions intervene on student demand <span class="citation" data-cites="RN4324 cottom2017lower">(<a href="#ref-cottom2017lower" role="doc-biblioref">Cottom, 2017</a>; <a href="#ref-RN4324" role="doc-biblioref">Holland, 2019</a>)</span>, thereby structuring college access pathways in ways that could amplify or diminish historic inequality in college access. The College Board played a pivotal role in transforming market research about enrollment from something done by individual universities to something done by third-party professionals <span class="citation" data-cites="RN4986">(<a href="#ref-RN4986" role="doc-biblioref">Litten et al., 1983</a>)</span>. This article offers one story about the quiet revolution that transformed college access into a sophisticated, supply-led enterprise. We argue that market research structures who colleges recruit, in ways that reinforce existing social stratification. The case of Market Segment Model and College Board geomarkets shows how market research – and its commodification into recruiting products – is a mechanism for social reproduction. [LAST TWO SENTENCES ARE REDUNDANT BUT BUT ARE TRYING TO DO SLIGHTLY DIFFERENT THINGS AND I LIKE THEM BOTH]</p>
</section>
<section id="quantification" class="level1">
<h1>Quantification</h1>
<!--
CUT GENERAL PARAGRAPH ON REPRODUCTION

Within the sociology of education, @RN2377 describes education as a sieve, allocating people to opportunities in socially stratified, capitalist societies. This role highlights "Max Weber's core insight that education has a dual character" [@RN2377, p. 129], on one hand, serving social mobility by redistributing access to privileged positions and, on the other, serving social reproduction by granting privileged families disproportionate access to the educational institutions that confer pathways to privileged positions. Similarly, @RN4873 describe schools and colleges as "sorting machines" that incorporate external categories (e.g., race, class), create categories (e.g., instructional tracks), and allocate students to categories. Initial category allocation affects subsequent allocation, such that school assignments and instructional track assignments affect college access, which affects employment assignments. "In evaluating schools as inequality regimes" @RN4873 \[p. 322\] argue, "the relevant question is not whether schools produce inequality; rather, the relevant questions are, when and where do schools produce inequality, \[and\] how do they do so." As @RN2377 show, whereas early research on social stratification sought to identify patterns of inequality [e.g., @RN4873; @RN290; @RN1268], the sociology of education is now more concerned with identifying the mechanisms underlying these patterns. 
-->
<p>We situate our study amidst scholarship on within scholarship on quantification as a mechanism that reproduces inequality. <span class="citation" data-cites="RN5007">Espeland &amp; Stephens (<a href="#ref-RN5007" role="doc-biblioref">2008, p. 402</a>)</span> define quantification as “the production and communication of numbers” (p.&nbsp;402) and introduce reacivity, discipline, and authority as three interrelated themes that describe the effects of quantification. Reactivity is the idea that salient quantitative measures cause people and organizations to change their behavior. Discipline is the idea that quantification causes actors to react in a particular way. Authority is the idea that quantification changes decision-making power, often weakening the discretion of local decision-makers.</p>
<p>Scholarship about U.S. News &amp; World Report (USNWR) Law School rankings demonstrate the reactivity, discipline, and authority effects of quantification <span class="citation" data-cites="RN5003 RN2356 RN2376 RN2375">(<a href="#ref-RN2356" role="doc-biblioref">Espeland &amp; Sauder, 2007</a>, <a href="#ref-RN5003" role="doc-biblioref">2016</a>; <a href="#ref-RN2376" role="doc-biblioref">Sauder, 2008</a>; <a href="#ref-RN2375" role="doc-biblioref">Sauder &amp; Espeland, 2009</a>)</span>. Developed as a means of informing prospective students about quality, rankings had the intended effect of affecting. Rankings also affected hiring decisions of firms because clients evaluated firms based on the prestige of law schools attended by firm lawyers. Once law schools realized that “important groups of constituents — students, faculty, trustees, employers, other media — were using rankings to make decisions that had large consequences for schools [then] schools felt pressured to take them seriously” <span class="citation" data-cites="RN5007">(<a href="#ref-RN5007" role="doc-biblioref">Espeland &amp; Stephens, 2008, p. 415</a>)</span>. Rankings <em>disciplined</em> the behavior of law schools. For example, applicants with characteristics valued by the rankings system (e.g., LSAT scores) became more important for decisions about admissions and merit aid <span class="citation" data-cites="RN5003">(<a href="#ref-RN5003" role="doc-biblioref">Espeland &amp; Sauder, 2016</a>)</span>. Rankings also weakened the <em>authority</em> of admissions directors and admissions officers to make independent decisions about which applicants to admit, ideal class size, and curricular offerings <span class="citation" data-cites="RN5003">(<a href="#ref-RN5003" role="doc-biblioref">Espeland &amp; Sauder, 2016</a>)</span>. <!--
In a process akin to sports analytics in Moneyball \[CITE MICHAEL LEWIS\], we suggest that market research replaces the wisdom and authority of local admissions counselors.    --></p>
<p>The analysis of UK League Tables by <span class="citation" data-cites="RN5005">McArthur &amp; Reeves (<a href="#ref-RN5005" role="doc-biblioref">2022</a>)</span> show how quantification can be a mechanism of social reproduction. As part of a broader <em>New Public Management</em> effort to infuse market competition within public providers <span class="citation" data-cites="RN161">(<a href="#ref-RN161" role="doc-biblioref">Walsh, 1995</a>)</span>, the UK government began publishing school “league tables” in 1992. League tables ranked schools based on student performance on high-stakes national exams taken at age 16. Using Census data on occupational class measured at the local authority level (similar to a U.S. county), <span class="citation" data-cites="RN5005">McArthur &amp; Reeves (<a href="#ref-RN5005" role="doc-biblioref">2022</a>)</span> find that localities with higher performing schools experienced growth in the share of managerial/professional households following the adoption of league tables and a decline in the share of working-class households. Additionally, using longitudinal household survey data, managerial/professional households were more likely to move to localities with higher ranked schools following the introduction of school league tables. With respect to mechanisms, league tables facilitate making evaluative comparisons between schools regardless of geographic proximity. They also discipline households and schools to conceive of school quality in terms of test scores, which are substantially a function of the class composition of schools. Compared to working-class parents, parents with professional/managerial occupations are more aware of school league tables and have financial resources necessary to move to neighborhoods near a “good” school. Therefore, league tables contributed to social reproduction because managerial/professional households respond to consumer-facing metrics by moving to more expensive neighborhoods, near higher performing schools. <!-- THIS IS RATCHET EFFECT STUFF. I CUT IT BECAUSE YOU HAVEN'T INTRODUCED THE IDEA OF RATCHET EFFECT
Schools that performed well on initial league tables tended to be schools with a high share of professional/managerial families. Therefore, quantification takes a snapshot of existing social stratification and that snapshot becomes a power unto itself, amplifying the effect of previous strctural inequality on subsequent structural inequality.
--></p>
<!-- THIS IS THE CUT TRANSITION PARAGRAPH
In the broader quantification literature, critical data studies [e.g., @RN4975; @RN4849; @RN4772] and sociological analyses of technology and inequality [e.g., @RN4778; @RN4786; @RN4877; @RN4810] introduce concepts salient to the analysis of market research. Our focus is on "selection devices," which utilize some combination of inputs and discretion to categorize places, people, and organizations for the purpose of allocating opportunities or interventions [@RN4778; @RN5012].
-->
<p>In the interdisciplinary literature on quantification <span class="citation" data-cites="RN5008">(<a href="#ref-RN5008" role="doc-biblioref">Mennicken &amp; Espeland, 2019</a>)</span>, the discussions of correlation and homophily by <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021</a>)</span> introduce concepts that are salient to the analysis of market research. Chapter 1 of <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021</a>)</span> is <em>Correlating Eugenics</em>. Correlation measures the extent to which two or more variables move together. The Pearson Correlation Coefficient was developed by the 19th Century statisticians and “biometric eugenicists” Francis Galton and his student Karl Pearson <span class="citation" data-cites="RN4975">(<a href="#ref-RN4975" role="doc-biblioref">Chun, 2021</a>)</span>. <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021, p. 50</a>)</span> writes that “correlation grounds big data’s so-called revolutionary potential. As Wired editor Chris Anderson infamously declared in his 2008 editorial ‘The End of Theory,’ big data proved that ‘correlation supersedes causation, and science can advance even without coherent models, unified theories, or really any mechanistic explanation at all.’” Predictive analytics are developed in two steps. First, apply statistical techniques to previous cases (training data) in order to identify factors positively and negatively associated with an outcome of interest. Second, apply these results (e.g., regression coefficients) to future cases in order to make predictions and to assign levels of risk to each case. These models predict outcomes based on correlations without requiring knowledge about underlying causal relationships. <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021</a>)</span> provides the example of <span class="citation" data-cites="RN4989">Kosinski, Stillwell, &amp; Graepel (<a href="#ref-RN4989" role="doc-biblioref">2013</a>)</span>, who develop a method to predict sensitive personal attributes (e.g., gender, political party) based on Facebook Likes.</p>
<p>Due to data limitations, predictive analytics often utilize “proxy” variables <span class="citation" data-cites="RN4849 RN4975">(<a href="#ref-RN4975" role="doc-biblioref">Chun, 2021</a>; <a href="#ref-RN4849" role="doc-biblioref">O’Neil, 2016</a>)</span>, which are variables that are correlated to a variable of interest. For example, “e-scores” utilize proxy variables to identify “people like you” and then predict your buying behavior based on the past buying behavior of these others. <span class="citation" data-cites="RN4849">O’Neil (<a href="#ref-RN4849" role="doc-biblioref">2016, p. 146</a>)</span> states that “the modelers for e-scores have to make do with trying to answer the question ‘How have people like you behaved in the past?’ when ideally they would ask, ‘How have you behaved in the past?’” We observe similar behavior in market research about college access, when enrollment managers use ‘which colleges did students near you consider’ as a proxy for, ‘which colleges would you consider?’</p>
<p>Many studies show that using correlational models make predictions reproduces structural inequality. The correlations observed during the training data stage are a snapshot of relationships between variables at a particular point of time. These correlations may be a function of enduring structural inequality, but underlying causes are not considered by applications of predictive models. <span class="citation" data-cites="RN4794">Burrell &amp; Fourcade (<a href="#ref-RN4794" role="doc-biblioref">2021, p. 224</a>)</span> state that “predicting the future on the basis of the past threatens to reify and reproduce existing inequalities.” Therefore, disproportionately targeted/excluded populations are predicted to have a higher risk of an outcome, which amplifies disproportionate targeting/exclusion. This phenomenon whereby has been termed the “ratchet effect” <span class="citation" data-cites="RN4851">(<a href="#ref-RN4851" role="doc-biblioref">Harcourt, 2015</a>)</span> and “pernicious feedback loops” <span class="citation" data-cites="RN4849">(<a href="#ref-RN4849" role="doc-biblioref">O’Neil, 2016</a>)</span>. An often cited example is the LSI-R recidivism model which predicts a prisoner’s chances of re-arrest and is used by 24 states <span class="citation" data-cites="RN4849">(<a href="#ref-RN4849" role="doc-biblioref">O’Neil, 2016</a>)</span>. Because the algorithm uses zip code as an input, people who live in highly policed neighborhoods have a higher predicted probability of being arrested, which leads to more policing in those neighborhoods, which perpetuates racialized inequality in arrests. Note that predictive models such as the LSI-R model are not merely used for social science purposes. Rather, they reproduce structural inequality because they direct the allocation of future resources based on a snapshot of historical inequality.</p>
<p>Chapter 2 of <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021</a>)</span>, <em>Homophily, or the Swarming of the Segregated Neighborhood</em>, argues that homophily often underlies the use of correlation to predict future behavior. Homophily means that actors who share common characteristics are likely to form connections with one another. The ubiquitous colloquialism is “birds of a feather flock together.” Homophily is a core assumption for network science <span class="citation" data-cites="mcpherson2001birds">(<a href="#ref-mcpherson2001birds" role="doc-biblioref">McPherson, Smith-Lovin, &amp; Cook, 2001</a>)</span>, in which actors (e.g., high school students) are linked to one another through direct and indirect network ties (e.g., submit SAT scores to the same college). Because network science often draws from rational choice theory, it assumes that homophily is the result of voluntary action by individuals, thereby “eras[ing] historical contingencies, institutional discrimination, and economic realities” <span class="citation" data-cites="RN4975">(<a href="#ref-RN4975" role="doc-biblioref">Chun, 2021, p. 95</a>)</span> that underlie behavior consistent with homophily. <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021</a>)</span> problematizes the idea that homophily is a naturally occurring phenomenon. In commercial social networks, such as Facebook, Twitter/X, and TikTok, homophily is programmed into the algorithms that create connections between users.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Within market research, homophily is central to geodemography and the creation of market segments. Geodemography emerged in the 1970s as a branch of market research that estimates the behavior of consumers based on where they live <span class="citation" data-cites="RN4878">(<a href="#ref-RN4878" role="doc-biblioref">Burrows &amp; Gane, 2006</a>)</span>. Market segments are subgroups within a larger market that have similar consumer demand. Early geodemographic classifications of consumers (e.g., PRIZM by Claritas Corporation) were derived from publicly available Census data, which disaggregated data to the zip code level <span class="citation" data-cites="RN4957">(<a href="#ref-RN4957" role="doc-biblioref">McKelvey, 2022</a>)</span>. The Claritas Corporation argued – and had a financial incentive to do so – that people living near one another share similar consumer preferences. Therefore, geographic localities could be categorized into market segments that would be useful for direct mail marketing campaigns. Later, the development of individual credit scores (e.g., FICO score) enabled merchants to classify consumers into many, fine-grained groups <span class="citation" data-cites="RN4877">(<a href="#ref-RN4877" role="doc-biblioref">M. Poon, 2007</a>)</span>. <span class="citation" data-cites="RN4810">M. Fourcade &amp; Healy (<a href="#ref-RN4810" role="doc-biblioref">2013</a>)</span> introduce the concept “classification situations” to describe the expansion of actuarial techniques to categorize customers into many, ordinally ranked groups. Merchants and lenders began tying these classifications to tiered products that targets different consumer groups with different levels of benefits and costs <span class="citation" data-cites="RN5015">(<a href="#ref-RN5015" role="doc-biblioref">Marion Fourcade &amp; Healy, 2024</a>)</span>. For example, “payday loans” charge high interest rates to consumer groups that were previously denied credit altogether. Classification situations engender markets where a vertical hierarchy of products are targeted to a vertical hierarchy of consumers. <!--
ORIGINAL TEXT ABOUT GEODEMOGRAPHIC CLASSIFICATION SYSTEMS

Clusters were given evocative names like "Blue Blood Estates," "\[Archie\] Bunker's Neighbors", and "Share Croppers." Because U.S. publicly available U.S. Census data disaggregated data only to the zip code-level, the Claritas Corporation had a strong incentive to argue that consumer behavior within zip codes was very similar [@RN4957]. @RN4565 emulated the behavior of Claritas by developing the *Segment Analysis Service: An Educationally Relevant Geodemographic Tagging Service*, which was an "add-on" to the *Student Search Service* student list product. Describing its conceptual underpinnings, @RN4565 [p. 1] states, "the basic tenet of geodemography is that people with similar cultural backgrounds, means, and perspectives naturally gravitate toward one another or form relatively homogeneous communities; in other words, birds of a feather flock together." The Segment product allocated each high school and each census tract into a distinct "educational neighborhoods" thought to reflect useful market segments for colleges looking for students.

PREVIOUS TEXT ABOUT CLASSIFICATION SITUATIONS
Related to the creation of market segments, @RN4810 introduce the concept "classification situations" to describe the expansion of actuarial techniques to categorize customers into many, ordinally ranked groups. Historically, classifications were binary. Consumers with "good" credit were offered loans and those with bad credit were not. The innovation of individual FICO scores -- and, later, other credit scores -- enabled merchants to classify consumers into many, fine-grained groups or along a continuum. Merchants and lenders began tying these classifications to tiered products that targets different consumer groups with different levels of benefits and costs [@RN5015]. People previously denied credit were now granted credit on different terms. For example, "payday loans" charge high interest rates to consumer groups that were previously denied credit altogether. Thus, at the bottom of the continuum, contemporary classification situations produce "predatory inclusion" -- exemplified by payday loans and for-profit colleges -- which is the logic of "including marginalized consumer-citizens into ostensibly democratizing mobility schemes on extractive terms" [@RN4774, p. 443].

Negative consequences of homophily
Chun (2021) discusses the negative consequences arising from homophily.Second, when we “engineer homophily” – through algorithms or policies – we make it less likely for heterophily to emerge, eliminating possibilities – of friendships, of matches – that may have occurred in the absence of such engineering.
--></p>
<p>Reviewing recent scholarship on quantification, <span class="citation" data-cites="RN5006">Berman &amp; Hirschman (<a href="#ref-RN5006" role="doc-biblioref">2018</a>)</span> argue that quantification has effects to the extent that stakeholders care about the numbers. Law school rankings <span class="citation" data-cites="RN5003">(e.g., <a href="#ref-RN5003" role="doc-biblioref">Espeland &amp; Sauder, 2016</a>)</span> and school league tables <span class="citation" data-cites="RN5005">(e.g., <a href="#ref-RN5005" role="doc-biblioref">McArthur &amp; Reeves, 2022</a>)</span> seem to exemplify this sort of salience. Widely known studies of quantification in education tend to study consumer-facing quantification. To our knowledge, prior research on quantification in education has not examined how third-party market research classifies consumers. This manuscript analyzes “market segment model” <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983</a>)</span>, which categorized high school students into vertical market segments and simultaneously created local “geo-markets” that were evaluated based on their composition of student market segments. The market segment model became the basis for the College Board <em>Enrollment Planning Service</em> (EPS), which advised colleges which geo-markets to target. <span class="citation" data-cites="RN5021">Noel-Levitz (<a href="#ref-RN5021" role="doc-biblioref">1998</a>)</span> reports that in 1995, 37% of 4-year public universities and 49% of 4-year private universities used EPS, while 41% of 4-year publics and 16% of 4-year privates used ACT’s market analysis service product, which was similar to EPS. Geo-markets later became a filter in the College Board <em>Student Search Service</em> student list product, which is utilized by the vast majority of public and private universities. <!--
CUT COMMENTS ON SALIENCE
By contrast, many quantification projects -- for example, human rights indicators -- have "little oomph" [@RN5006, p. 265]. FROM BERMAN & HIRSCHAN PAGE 263: "Merry demonstrates how human trafficking indicators largely sit on the shelf because no audience for them has been created." 
--> Scholarship on predictive analytics <span class="citation" data-cites="RN4975 RN4849">(<a href="#ref-RN4975" role="doc-biblioref">Chun, 2021</a>; <a href="#ref-RN4849" role="doc-biblioref">O’Neil, 2016</a>)</span> suggests the mechanisms by which market research reproduces structural inequality. Based on a snapshot of existing social stratification, market research matches verticially categorized consumers to vertically categorized producers, thereby amplifying the effect of initial stratification on subsequent stratification. Unlike studies like <span class="citation" data-cites="RN5005">McArthur &amp; Reeves (<a href="#ref-RN5005" role="doc-biblioref">2022</a>)</span> we cannot show the effect of quantification. However, this study provides inisight about the mechanism underlying the effect. By analyzing and simulating <em>Student Search Service</em> purchases that filter on geo-markets we can show <em>how</em> the geo-markets reproduce historical class-based and race-based inequality in college access.</p>
</section>
<section id="the-market-segment-model-and-college-board-geomarkets" class="level1">
<h1>The Market Segment Model and College Board Geomarkets</h1>
<p><!--Historically, College Board partnered with Members to develop projects that later became revenue-generating products for College Board.--> As a member organization, several College Board products developed from joint collaborations with administrators or professors from member institutions. During the 1970s, under the leadership of Larry Litten, then director of institutional research, Carleton College pionered applying market research to student recruiting. In the late 1970s, College Board provided Carleton College with funding and data for a six-year project that analyzed college choice decisions by households in six metropolitan areas. This project was the basis for the landmark book <em>Applying Market Research in College Admissions</em> <span class="citation" data-cites="RN4986">(<a href="#ref-RN4986" role="doc-biblioref">Litten et al., 1983</a>)</span>, published by College Board, and was the basis for the College Board Admitted Student Questionnaire (ASQ), a revenue-generating product that provides colleges with information about admitted students – those who enrolled and who did not enroll. Litten would later become Associate Director of the Consortium of Financing Higher Education (COFHE), a consortium of 30 selective private universities founded in the mid-1970s.</p>
<p>In 1978, Robert Zemsky, a University of Pennsylvania professor, was asked by the President to figure out, “‘Who thinks about Penn?’” and “‘What other institutions do they think about when they think about us?” <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983, p. x</a>)</span>. To answer these questions, Zemsky began working with the Market Research Committee of the Consortium on Financing Higher Education (COFHE). As the project project became more ambitious, the researchers reached out to College Board because “we needed a database that described most institutions and most studentsCoincidentally, the Board was reviewing its own efforts to help colleges estimate their enrollment potential, efforts which had faltered largely because the smallest demographic unit used in tehse analyses was the state’ <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983, p. x</a>)</span>. In 1979, College Board began providing data and funding for what became the <em>Comprehensive Undergraduate Enrollment Planning Project (CUEPP)</em>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 4</a>)</span> write that,</p>
<blockquote class="blockquote">
<p>For our analysis, we sought not a complex mathematical model, but a straightforward classification system that would track the pattern of SAT-score submissions to create a map of student choice. The Market Segment model that we developed was nothing more than a set of simple rules for disaggregating high school seniors into similar groups. The model worked because students, once so disaggregated, appeared to behave in remarkably consistent ways.</p>
</blockquote>
<p><strong>Creating the Market Segment Model.</strong> Considering the <span class="citation" data-cites="RN5007">Espeland &amp; Stephens (<a href="#ref-RN5007" role="doc-biblioref">2008</a>)</span> [p.&nbsp;402] definition of quantification as “the production and communication of numbers,” the Market Segment Model is an effort to quantify and communicate the knowledge that admissions officers have about student demand. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 4</a>)</span> state that “our initial task was to define enrollment markets in a manner consistent with admissions officers’ intuitive understanding of student pools.” They created “three types of boundaries” <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983, p. 11</a>)</span>, region, state, and community. The three regions were New England, Middle States, and the South. Next, “we divided each state into as few as two and as many as thirty community-based enrollment markets or pools, for a total of 143 separate markets” [in New England, Middle States, and the South].</p>
<p>These enrollment markets, later called “geomarkets” by the College Board Enrollment Planning Service were intended to be consistent with the conception of a catchment market from the perspective of admissions counselors. We know little about how geomarkets were created. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> write that,</p>
<blockquote class="blockquote">
<p>In many cases, the market boundaries match formal political and educational divisions, reflecting natural channels of communication. Each major metropolitan area is composed of several markets, usually corresponding to the inner city, a first ring of suburbs, and an outer ring of suburbs. In more sparsely populated areas, communities are sometimes combined in order to make the analysis meaningful.”</p>
</blockquote>
<p>Having defined these geographic boundaries, high school students were categorized into one of four different <em>market segments</em> – local, in-state, regional, and national – based on SAT score-sending behavior. Each institution a student sends SAT scores to can be defined as “local” (institution is in the same local market that the student lives in), “in-state” (same state but different local market), “regional” (same region but different state), or “national.” In turn, a “local” student submits more SAT scores to local institutions than they do to in-state, regional, or national institutions. An “in-state” student submits more SAT scores to in-state institutions than they do to local, regional, or national institutions, etc. <!--
A "regional" student submits more SAT scores to regional institutions than they do to local, in-state, or national institutions. A "national" student submits more SAT scores to national institutions than they do to local, in-state, or regional institutions.
--></p>
<p>The two primary outputs of the market segment model are the (1) Market Segment Profile and (2) the Institutional Profile. The Market Segment Profile, which was produced separately for each of the 143 geo-markets, provides information about the number and characteristics of students in each market segment. <a href="#tbl-market-segment-characteristics" class="quarto-xref">Table&nbsp;1</a> reproduces a partial, simplified version of the bottom panel of <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, fig. 2.1</a>)</span> which represents the Market Segment Profile for “Connecticut Market 3: Fairfield County.” <a href="#tbl-market-segment-characteristics" class="quarto-xref">Table&nbsp;1</a> has separate columns for each market segment (local, in-state, regional, national) and rows show the number of test-takers and characteristics of test-takers. For example, there were 550 “local” students in Fairfield county and these students submitted SAT scores to 2.8 postsecondary institutions on average. By contrast, there were 1,664 “regional” students who submitted test scores to 4.8 institutions on average. For local students, 11.2% had family income greater than $35,000 and 9% had both parents with a BA. For regional students, 41.9% had family income greater than $35,000 and 34.0% had both parents with a BA. Each Market Segment Profile also present information about the institutions that students from each segment sent scores to.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>INSERT <a href="#tbl-market-segment-characteristics" class="quarto-xref">Table&nbsp;1</a> ABOUT HERE</p>
<p>The <em>Institutional Profile</em> describes students who send scores to a particular institution and which majors these students are interested in. For each institution, institutional profiles are created separately for students from a particular local market, for all students in a state, or all students in a region. <a href="#tbl-sample-institutional-profile" class="quarto-xref">Table&nbsp;2</a> reproduces a partial, simplified version of <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, fig. 2.3</a>)</span>, the institutional profile of an anonymous institution for students from Fairfield County, CT. <a href="#tbl-sample-institutional-profile" class="quarto-xref">Table&nbsp;2</a> shows that 58 in-state students submitted SAT scores to the institution. These 58 students represented 4.8% of the total 1,199 in-state students from Fairfield County. 69 regional students sent scores to the institution, representing 4.1% of all 1,664 regional test-takers. Of these 69 regional students, 35 expressed interest in majoring in the liberal arts. These 35 students represent 7.0% of all regional students from Fairfield County who expressed interest in the liberal arts.</p>
<p>INSERT <a href="#tbl-sample-institutional-profile" class="quarto-xref">Table&nbsp;2</a> ABOUT HERE</p>
<p><span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> argue that the Institutional Profile and the Market Segment Profile enable admissions officers to know where to look for students and which institutions are competing for those students (p.&nbsp;25):</p>
<blockquote class="blockquote">
<p>The Institutional Profile and the Market Segment Profile quantify the admission officers’ intuitive grasp of market structure. Structure here carries a dual meaning, connoting both the structure of student choice and the structure of institutional competitionThis two-sided interpretation furnishes the essential framework for planning by individual colleges and universitiesTo draw effectively on its own natural constituency, a college not only must contact the “right” kind of students — that is, students who are predisposed toward that type of institution – but also must persuade them of its special character. This means knowing the competition as well as the clientele.</p>
</blockquote>
<p><strong>Correlations</strong>. Chapter 3 of <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> – “A Sense of Place: Students, Families, and Communities” – identifies the student characteristics associated with being in the local, in-state, regional, or national market segment and examines the extent to which these relationships hold across states and local markets. The analyses identify four variables – educational aspirations, parental education, scholastic aptitude, and family income – that predict score sending behavior, both individually and in combination. <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983, p. 33</a>)</span> state that these four variables “reflect the basic social patterns of the nation. It would have been surprising if these were not the four social variables that best explained the patterns of college choice.”</p>
<p><span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> summarize their correlational analyses using authoritative language. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, pp. 34–35</a>)</span> asserts, “it is hard to overemphasize the importance of this statistical pattern. Social data seldom line up as we expect The information derived from the Market Segment Model, however, is a remarkably ordered set of data, consistent in its relationships, that reflects the basic social and economic patterning associated with the structure of college choice.” With respect to family income, <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 33</a>)</span> state that “these data allow us to say with considerable confidence that local and in-state students are not likely to come from families in which both parents have received college educations” and “the implication is simply that college-educated parents instill in their children more wide-ranging educational aspirations.” Commenting on family income, <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 33</a>)</span> write that “we could predict that all local students would come from moderate-income or low-income families and be wrong only 5.5 percent of the time.” Further analyses reveal that the SAT score is the most important predictor of score-sending behavior, followed by parental education, family income, and educational aspirations. Considering prior research showing that SAT scores are substantially a function of social origin <span class="citation" data-cites="RN1273">(<a href="#ref-RN1273" role="doc-biblioref">Sewell &amp; Shah, 1967</a>)</span>, the Market Segment Model implicitly and explicitly states that student demand for higher education is mostly a function of social origin. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> also find that the SAT score, parental education, and family income predict student score-sending behavior at the local geo-market level.</p>
<p>However, geomarkets differ in the relative abundance of students with particular socioeconomic characteristics and this has practical implications for recruiting. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> recommend that colleges target geo-markets with desirable compositions of socioeconomic characteristics and student market segment. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 44</a>)</span> describes a hypothetical college that wants to target regional and national students in New England and is considering whether to expend limited recruiting efforts in the Boston geo-market – which was relatively low-income in 1980 – or in more affluent geo-markets nearby:</p>
<blockquote class="blockquote">
<p>Where would you concentrate your energies? Ideally, you would seek communities with a high proportion of students already predisposed toward institutions such as your own. The Market Segment Model would provide this information through segment percentages for the community in question. Further classification of students by social attributes allows you to identify a group for mailings or recruitingIf you were to recruit in Boston, only about two out of every ten students with fewer than two attributes would likely listen, while slightly less than half of the students with two or more attributes would be receptive. Your efforts would surely be better directed toward three of the four communities in the bottom band, Manchester, Hartford, and Fairfield County. Simply by knowing a little bit about the students’ backgrounds and academic records you could quickly focus your attention on those most likely to consider your kind of institution. Indeed, in Fairfield County alone you could reach more than 40 percent of your “primary target” population – that is, students with a greater than 75-percent probability of concentrating their college choices among institutions like your own.”</p>
</blockquote>
<p><strong>EPS and College Board Geomarkets</strong>. In 1984, College Board created the Enrollment Planning Service (EPS) based on the Market Segment Model <span class="citation" data-cites="RN4987 RN4980">(<a href="#ref-RN4987" role="doc-biblioref">College Board, 2012</a>; <a href="#ref-RN4980" role="doc-biblioref">Takamiya, 2005</a>)</span>. Each institution purchasing EPS information services would obtain access to the Market Segment Report for each local market. They also received the Institutional Profile – their own and that of competitors – for each local market. Promotional material highlights the themes of “locate the students you want” <span class="citation" data-cites="RN5019_2003">(<a href="#ref-RN5019_2003" role="doc-biblioref">Board, 2003</a>)</span> and “focus your valuable time and resources on the right prospects” <span class="citation" data-cites="RN5019">(<a href="#ref-RN5019" role="doc-biblioref">College Board, 2005</a>)</span>. <span class="citation" data-cites="RN5019_2010">College Board (<a href="#ref-RN5019_2010" role="doc-biblioref">2010</a>)</span> promotional material describes EPS as:</p>
<blockquote class="blockquote">
<p>the analysis tool that pinpoints the schools and geomarkets where your best prospects are most likely to be found. You can research your existing (or new) markets using selection criteria and locate your top prospects in various ways – by states, geomarkets, counties, Zip codes, high schools and international regions. EPS provides you with comprehensive reports on your markets, your position in those markets, and your copetition.”</p>
</blockquote>
<!--
@RN5019 [2005]
> The marketing software that pinpoints the schools and geomarkets where your best prospects are most likely to be found. With the click of a mouse, EPS provides you with comprehensive reports on your markets, your position in those markets, and your competition. Focus your valuable time and resources on the right prospects 

Software documentation by @RN5017 states that "EPS market codes are proprietary market codes owned by the College Board and are used to categorize external organizations and people into geographical areas, mostly in the United States. Some admissions offices use EPS market codes to focus their recruiting efforts in geographic areas in which they believe they will be the most successful."
-->
<p>Whereas <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>, Appendices B1-B3)</span> identified 143 geo-markets covering the New England, Middle States, and South region, EPS created geo-markets for the remaining U.S. states, with 304 geo-markets in total. <span class="citation" data-cites="RN4988">College Board (<a href="#ref-RN4988" role="doc-biblioref">2023</a>)</span> shows the College Board geo-markets circa 2023. Interestingly, the geo-markets for New England, Middle States, and the South remain nearly identical to those developed by <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span>. Concrete information about how EPS created the remaining geomarkets is elusive. Documentation and promotional material suggests that geomarket borders were chosen based on a combination of formal geographic borders (e.g., counties) as well as proprietary College Board data designed to identify geographic areas with different college-going behaviors.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>Although how we lack clarity about how geomarkets were created, we expect substantial socioeconomic inequality between geomarkets in large metropolitan areas. Given the extent of class- and race-based residential segregation in the U.S., it would be surprising to not observe such inequality. Additionally, <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> created geomarkets in service of the Market Segment Model. The Market Segment Model argues that socioeconomic status drives whether students belong to the local, in-state, regional, or national market segment. In turn, geomarkets are described by the relative numbers of local, in-state, regional, or national students, which is substantially a function of socioeconomic status. The language of <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, pp. 11–12</a>, quoted above)</span> suggests that geomarket borders within large metropolitan areas may have been drawn in ways that separate affluent from less affluent communities. We present the following hypothesis:</p>
<p><strong>H1</strong>. In large metropolitan areas that contain multiple geomarkets, we expect significant socioeconomic inequality (e.g., income, parental education) between geomarkets.</p>
<p>We expect substantial racial inequality between geomarkets in large metropolitan areas for several reasons. Interestingly, the Market Segment Model is explicitly based on socioeconomic stratification, but <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> do not mention race once. However, U.S. cities are characterized be extreme historic and contemporary residential racial segregation <span class="citation" data-cites="RN4779 rothstein2017color">(<a href="#ref-RN4779" role="doc-biblioref">Korver-Glenn, 2022</a>; <a href="#ref-rothstein2017color" role="doc-biblioref">Rothstein, 2017</a>)</span>. Structures built upon racialized structures are racialized structures. <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021</a>)</span> argues that unless designers intentionally consider racial segregation, selection devices that categorize people based on geographic location are likely to reproduce historical race-based inequality in opportunity. Second, geomarket borders may have been drawn along class divides. There is a strong correlation between race and wealth <span class="citation" data-cites="RN4884">(<a href="#ref-RN4884" role="doc-biblioref">Kraus, Onyeador, Daumeyer, Rucker, &amp; Richeson, 2019</a>)</span>. Third, geo-market borders may have been drawn in a way that follows the countours of racial segregation in residential housing. Examples include: the “South and South Central Los Angeles” geomarket (CA21); the “City of Oakland” geomarket (CA07), which is surrounded by the “Alameda County excluding Oakland” geomarket (CA08); and the “Wayne County Detroit” geomarket (MI01), which is surrounded by the “Detroit’s Northern Suburbs” (MI02) and “Ann Arbor” (MI03) geomarkets. Although these arguments are speculative, the extent of racial inequality between geomarkets can be assessed empirically. We present the following hypothesis:</p>
<p><strong>H2</strong>. In large metropolitan areas that contain multiple geomarkets, we expect significant racial inequality (e.g., income, parental education) between geomarkets.</p>
<p>We argue that the Market Segment Model, geomarkets, and their commodification within EPS exemplify concerns about the application of correlational analysis. The data on 1980 SAT score-sending behavior analyzed by <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> can be conceived as training data. These training data were used to define geomarkets (e.g., how many geomarkets in a metropolitan area is partially a function of the number of test-takers) and to identify student characteristics associated with the local, in-state, regional, and national market segments. These analyses found that student demand for different kinds of colleges was largely a function of social origin, and that student demand within a geo-market was largely a function of the class composition of the geo-market. However, <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span> did not interrogate the historical and contemporary structural inequalities that produced observed patterns of social stratification. Instead, the Market Segment Model encouraged colleges to use this snapshot of student demand as the basis for future decisions about which communities and prospective students should be targeted by college recruiting campaigns. This process exeemplifies the “ratchet effect” <span class="citation" data-cites="RN4851">(<a href="#ref-RN4851" role="doc-biblioref">Harcourt, 2015</a>)</span> and “pernicious feedback loops” <span class="citation" data-cites="RN4849">(<a href="#ref-RN4849" role="doc-biblioref">O’Neil, 2016</a>)</span> whereby predicting the behavior of future individuals based on the behavior of past individuals “threatens to reify and reporduce existing inequalities” <span class="citation" data-cites="RN4794">(<a href="#ref-RN4794" role="doc-biblioref">Burrell &amp; Fourcade, 2021, p. 224</a>)</span>. This process also exemplifies concerns about proxy variables whereby selective colleges view privileged social class as a proxy for desirable students and this creates an incentive to focus recruiting efforts on communities that have these characteristics. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 44</a>)</span> corroborates these concerns:</p>
<blockquote class="blockquote">
<p>On occasion, senior spokespersons for the profession worry that students outside the main market areas remain forgotten and hence, unchallenged. Inevitably, the increasing competition for students, the expense of travel and mailings, and internal political constraints compel institutions to concentrate their efforts where they will do the most good. The result is a natural reinforcing of the basic socioeconomic patterns that gave shape in the first place to the structure of college choice.</p>
</blockquote>
<p><strong>Homophily and Utilization</strong>. <em>The Company We Keep: Colleges and Their Competition</em> <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983, Chapter 4</a>)</span> shows that homophily is a core tenet of the Market Segment Model. The authors conduct a social network analysis that defines two institutions as being in competition with one another if at least 15% of students who sent SAT scores to one institution also sent scores to the other institution and vice-versa.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 42</a>)</span> sate, “we draw a fundamental conclusion about the structure of college choice: collegiate competition occurs principally between like institutions.”<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> Subsequent analyses investigate the tuition price and socioeconomic composition of institutions in competition with one another. Private selective colleges and private flagship universities compete directly for students, charge the highest prices, and enroll students with the highest socioeconomic status. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 72</a>)</span> describe these patterns as a natural process of homophily in which a vertical socioeconomic hierarchy of students is matched to a vertical hierarchy of universities:</p>
<!--[^10]: These patterns are similar to different offers for credit products in The Ordinal Society [@RN5015], except @RN5015 show that the matching of consumers to products is engineered by firms rather than naturally occurring.-->
<blockquote class="blockquote">
<p>We now know why students so seldom speak of their own social or family backgrounds in explaining how they go about choosing a college. They have no need to. Students describe themselves socially simply by telling us the colleges and universities in which they are interested. The layering of collegiate competition is primarily a socioeconomic layering. The hierarchical structure of collegiate competition largely reflects the stratified social and economic dimensions of the communities from which colleges draw their students. Competition among colleges, as admissions officers have told us for so long, is in fact, a matter of keeping company with one’s peers.</p>
</blockquote>
<p>Although this perspective is broadly consistent with mid-20th Century scholarship on social mobility <span class="citation" data-cites="RN915 RN1273">(<a href="#ref-RN915" role="doc-biblioref">Blau &amp; Duncan, 1967</a>; <a href="#ref-RN1273" role="doc-biblioref">Sewell &amp; Shah, 1967</a>)</span>, the Market Segment Model was the basis for the EPS market research product. Later, geomarkets were incorporated into the <em>Student Search Service</em> student list product. Commodification of the Market Segment Model “engineers homophily” <span class="citation" data-cites="RN4975">(<a href="#ref-RN4975" role="doc-biblioref">Chun, 2021</a>)</span> by taking a snapshot of existing stratification and then recommending that colleges utilize this snapshot as the basis for decisions about where to concentrate recruiting efforts. <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. 58</a>)</span> states that “correlations, do not simply predict actions; they also form them.” In itself, the Market Segment Model is simply a stylized depiction [HIRSCHMAN 2016 STYLIZED FACTS] of the structure of college choice, one that does not consider class-based and race-based structures that produced these patterns. Once the College Board inscribed the Market Segment Model into the EPS and Student Search Service Products, these products are likely to amplify the effect of historic structural inequalities on future opportunity structure by encouraging colleges to pursue local markets – and student segments within these local markets – in ways that are consistent with the patterns observed by <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983</a>)</span>.</p>
<p>Utilization of the Market Segment Model and geomarkets within the Enrollment Planning Service (EPS) raises concerns related to the quantification themes of reactivity, discipline, and authority introduced <span class="citation" data-cites="RN5007">(<a href="#ref-RN5007" role="doc-biblioref">Espeland &amp; Stephens, 2008</a>)</span>. <span class="citation" data-cites="RN5006">Berman &amp; Hirschman (<a href="#ref-RN5006" role="doc-biblioref">2018</a>)</span> argue that quantification has effects to the extent that stakeholders care about the numbers. Although EPS is a business-facing rather than a consumer-facing product, it has been a highly salient one. <span class="citation" data-cites="RN5021">Noel-Levitz (<a href="#ref-RN5021" role="doc-biblioref">1998</a>)</span> reports that in 1995, 37% of 4-year publics and 49% of 4-year privates used EPS, while 41% of 4-year publics and 16% of 4-year privates used ACT’s market analysis service product. We suggest that EPS disciplines colleges to approach recruiting in a manner consistent with the Market Segment Model. Colleges are encouraged to, first, choose geomarkets with a high number of desirable prospects and, second, plan recruiting efforts within selected geomarkets. Under the principle of homophily, selective colleges should target geomarkets with large numbers of affluent, college educated households, while low-income communities are left to local four-year and community colleges. Consistent with this perspective, EPS software documentation from <span class="citation" data-cites="RN5017">Oracle (<a href="#ref-RN5017" role="doc-biblioref">n.d.</a>)</span> describes how geomarkets – here, called “EPS market codes” – can be utlized:</p>
<blockquote class="blockquote">
<p>EPS (Enrollment Planning Service) is a geographic and demographic data service offered annually by the College Board to Colleges and Universities. EPS provides information to subscribing institutions about competitors, feeder schools, and demographic strengths and weaknesses. EPS market codes are proprietary market codes owned by the College Board and are used to categorize external organizations and people into geographical areas, mostly in the United States. Some admissions offices use EPS market codes to focus their recruiting efforts in geographic areas in which they believe they will be the most successful.</p>
</blockquote>
<p>EPS may also weaken the authority of local decision-makers. The Market Segment model sought to develop a concrete, data-driven framework that replicated the aggregate knowledge of local admissions officers <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983</a>)</span>. Once this knowledge is quantified and commodified into a product stored on a CD-ROM, the local expertise of admissions officers becomes less valuable. The EPS product increases the ability of a college admissions leader – working with College Board staff or an enrollment management consultant – to plan recruiting efforts centrally. In turn, admissions officers are relegated to a foot-soldier implementation role rather than being sought out for their local expertise about student demand.</p>
<p>Finally, we suggest that utilization of geomarket filters within the Student Search Service product is likely to amplify class-based and race-based disparities in college opportunity. In contrast to standardized selection devices (e.g., the FICO score algorithm), student list products are discretionary selection devices in that colleges have discretion of which filters they elect to select prospects. Compared to standardized selection devices, scholars tend to find that administrative discretion over selection devices causes structural inequality to increase <span class="citation" data-cites="RN4883 RN4881 RN4795">(<a href="#ref-RN4883" role="doc-biblioref">Castilla, 2008</a>; <a href="#ref-RN4795" role="doc-biblioref">Cotter, Medeiros, Pak, &amp; Thorson, 2021</a>; <a href="#ref-RN4881" role="doc-biblioref">Norris, 2022</a>)</span>. Even in the absence of explicit or implicit bias, discretionary selection devices can increase racial inequality when decision-makers have incomplete knowledge about how the inputs they choose are correlated with race. For example, research shows that Americans dramatically underestimate the magnitude of racial income inequality <span class="citation" data-cites="RN4884">(<a href="#ref-RN4884" role="doc-biblioref">Kraus et al., 2019</a>)</span>. As such, discretionary selection devices are particularly sensitive to inputs that are correlated with race but are perceived to be race-neutral.</p>
<p>Geomarkets are opaque in that geomarket borders may be unclear to someone purchasing student lists and very few people know how these borders were created. <span class="citation" data-cites="RN4849">O’Neil (<a href="#ref-RN4849" role="doc-biblioref">2016</a>)</span> argues that opacity in algorithmic products is intentional and is a core criterion of “weapons of math destruction.” Enrollment management professionals utilizing EPS and <em>Student Search Service</em> may interpret geomarkets as a race-neutral recruiting tool. When purchasing student lists, <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, p. X</a>)</span> suggest that affluent colleges should consider targeting affluent geomarkets. Student list purchases do not show how the characteristics of targeted prospects compare to the characteristics of the surrounding community. From this perspective, racial inequality from the use of geomarkets in student list purchases may be the unintentional result of using a seemingly race-neutral product. Furthermore, purchases that specify multiple filters (e.g., test scores, grades, intended major) including geomarkets can yield unintended racial inequality because administrators have incomplete knowledge about how the intersection of these filters interact with local patterns of segregation.</p>
<!-- CUT TEXT DEFINING COLORBLIND RACISM AND RACE-NEUTRAL RACISM
Colorblind racism describes ideology and associated behaviors that ignore the significance of race and racial discrimination [@RN5020]. The Market Segment Model can be seen as an example of colorblind racism. @RN4982 develop an analysis of the structure of college choice that ignores race but we contend that geo-markets are correlated with race. Race-neutral racism is racial inequality that results from using ostensibly race-neutral inputs that are systematically correlated with race [CITE] [e.g., @RN4775; @RN4786; @RN4975]. 
-->
<p><!-- CUT PARAGRAPH: WHY GEOMARKETS ARE WEAPONS OF MATH DESTRUCTION
The incorporation of geo-markets within the Student Search Service student list product raises concerns about the three characteristics of weapons of math destruction. First, geo-markets are opaque. The borders of a geomarket may be unclear to someone purchasing student lists and very few people know how these borders were created \[COULD TALK ABOUT PRODUCT UTILIZATION HERE; NOT CLEAR HOW GEOMARKETS INTERACT WITH OTHER STUDENT LIST FILTERS\]. Second, geo-markets scale. Each year, thousands of colleges purchase student lists and it is easy to filter purchases based on geo-markets in concert with other filters (e.g., SAT score, GPA). Third, geo-markets can cause damage. When a college decides to purchase names from one geo-market but exclude prospects from an adjacent geo-market, this affects which college students have an opportunity to attend. @RN4982 suggests that selective colleges focus on geomarkets with large numbers of affluent, college educated households, while low-income communities are left to local four-year and community colleges.
--></p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<p>Below, we use simulations and actual student list purchases that filtered on geomarkets. In purchases that filtered on test-score and/or GPA thresholds, we can simluate who would be included and excluded had certain geo-markets were been selected. In purchases that filter on geomarkets, we can get an initial sense of who is included in geomarkets targeted by regional state colleges versus research universities.</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>In their analysis of quantifying school quality in England, <span class="citation" data-cites="RN5005">McArthur &amp; Reeves (<a href="#ref-RN5005" role="doc-biblioref">2022, p. 517</a>)</span> observe that “one problem with school league tables is that the measures of school quality often merely reflect the social origins of those who attend a particular school.” Similarly, considering prior research showing that SAT scores are substantially a function of social origin <span class="citation" data-cites="RN1273">(<a href="#ref-RN1273" role="doc-biblioref">Sewell &amp; Shah, 1967</a>)</span>, the Market Segment Model argues that student demand for higher education is mostly a function of social origin.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-belkin2019-studata" class="csl-entry" role="listitem">
Belkin, D. (2019). For sale: <span>SAT</span>-<span>Takers</span>’ names. <span>Colleges</span> buy student data and boost exclusivity. <em>The Wall Street Journal</em>. Retrieved from <a href="https://www.wsj.com/articles/for-sale-sat-takers-names-colleges-buy-student-data-and-boost-exclusivity-11572976621">https://www.wsj.com/articles/for-sale-sat-takers-names-colleges-buy-student-data-and-boost-exclusivity-11572976621</a>
</div>
<div id="ref-RN4775" class="csl-entry" role="listitem">
Benjamin, R. (2019). <em>Race after technology: Abolitionist tools for the new <span>J</span>im <span class="nocase">c</span>ode</em>. Medford, MA: Polity.
</div>
<div id="ref-RN5006" class="csl-entry" role="listitem">
Berman, E. P., &amp; Hirschman, D. (2018). The sociology of quantification: Where are we now? <em>Contemporary Sociology-a Journal of Reviews</em>, <em>47</em>(3), 257–266. <a href="https://doi.org/10.1177/0094306118767649">https://doi.org/10.1177/0094306118767649</a>
</div>
<div id="ref-RN915" class="csl-entry" role="listitem">
Blau, P. M., &amp; Duncan, O. D. (1967). <em>The american occupational structure</em> (pp. xvii, 520 p.). New York: Wiley.
</div>
<div id="ref-RN5019_2003" class="csl-entry" role="listitem">
Board, C. (2003). Enrollment planning services. College Board. Retrieved from <a href="https://www.collegeboard.com/highered/ra/eps.html">www.collegeboard.com/highered/ra/eps.html</a>
</div>
<div id="ref-RN5016" class="csl-entry" role="listitem">
Board, C. (n.d.). <em>SAT trends dashboard report: Interpretive guide</em>. College Board. Retrieved from <a href="https://satsuite.collegeboard.org/media/pdf/sat-trends-dashboard-interpretive-guide.pdf">https://satsuite.collegeboard.org/media/pdf/sat-trends-dashboard-interpretive-guide.pdf</a>
</div>
<div id="ref-RN4794" class="csl-entry" role="listitem">
Burrell, J., &amp; Fourcade, M. (2021). The society of algorithms. <em>Annual Review of Sociology</em>, <em>47</em>, 213–237. <a href="https://doi.org/10.1146/annurev-soc-090820-020800">https://doi.org/10.1146/annurev-soc-090820-020800</a>
</div>
<div id="ref-RN4878" class="csl-entry" role="listitem">
Burrows, R., &amp; Gane, N. (2006). Geodemographics, software and class. <em>Sociology-the Journal of the British Sociological Association</em>, <em>40</em>(5), 793–812. <a href="https://doi.org/10.1177/0038038506067507">https://doi.org/10.1177/0038038506067507</a>
</div>
<div id="ref-RN4322" class="csl-entry" role="listitem">
Campbell, A. (2017). <em>Higher education marketing: <span>How</span> to master your admissions funnel</em>. Hop Online. Retrieved from <a href="https://hop-online.com/blog/higher-education-marketing-admissions-process/">https://hop-online.com/blog/higher-education-marketing-admissions-process/</a>
</div>
<div id="ref-RN4883" class="csl-entry" role="listitem">
Castilla, E. J. (2008). Gender, race, and meritocracy in organizational careers. <em>American Journal of Sociology</em>, <em>113</em>(6), 1479–1526. <a href="https://doi.org/10.1086/588738">https://doi.org/10.1086/588738</a>
</div>
<div id="ref-RN4935" class="csl-entry" role="listitem">
Chetty, R., Deming, D. J., &amp; Friedman, J. N. (2023). Diversifying society’s leaders? The causal effects of admission to highly selective private colleges. <em>National Bureau of Economic Research Working Paper Series</em>, <em>No. 31492</em>. <a href="https://doi.org/10.3386/w31492">https://doi.org/10.3386/w31492</a>
</div>
<div id="ref-RN4975" class="csl-entry" role="listitem">
Chun, W. H. K. (2021). <em>Discriminating data: Correlation, neighborhoods, and the new politics of recognition</em> (pp. xi, 327 pages). Cambridge, Massachusetts: The MIT Press.
</div>
<div id="ref-RN5019" class="csl-entry" role="listitem">
College Board. (2005). Enrollment planning services. College Board. Retrieved from <a href="https://www.collegeboard.com/highered/ra/eps.html">www.collegeboard.com/highered/ra/eps.html</a>
</div>
<div id="ref-RN5019_2010" class="csl-entry" role="listitem">
College Board. (2010). Enrollment planning services. College Board. Retrieved from <a href="https://www.collegeboard.com/highered/ra/eps.html">www.collegeboard.com/highered/ra/eps.html</a>
</div>
<div id="ref-RN4565" class="csl-entry" role="listitem">
College Board. (2011). <em>Segment <span>Analysis</span> <span>Service</span>: <span>An</span> educationally relevant geodemographic tagging service</em>. <span>College Board</span>. Retrieved from <a href="https://secure-media.collegeboard.org/mSSS/media/pdf/segment-analysis-service-overview.pdf">https://secure-media.collegeboard.org/mSSS/media/pdf/segment-analysis-service-overview.pdf</a>
</div>
<div id="ref-RN4987" class="csl-entry" role="listitem">
College Board. (2012). <em>Welcome to the college board</em>. College Board. Retrieved from <a href="https://secure-media.collegeboard.org/homeOrg/content/pdf/welcome_to_the_college_board_fullversion.pdf">https://secure-media.collegeboard.org/homeOrg/content/pdf/welcome_to_the_college_board_fullversion.pdf</a>
</div>
<div id="ref-RN4988" class="csl-entry" role="listitem">
College Board. (2023). <em>Detailed connections geography maps: Reach more students where they are</em>. College Board. Retrieved from <a href="https://cbsearch.collegeboard.org/media/pdf/connections-geographies.pdf">https://cbsearch.collegeboard.org/media/pdf/connections-geographies.pdf</a>
</div>
<div id="ref-RN4795" class="csl-entry" role="listitem">
Cotter, K., Medeiros, M., Pak, C., &amp; Thorson, K. (2021). "Reach the right people": The politics of "interests" in <span>F</span>acebook’s classification system for ad targeting. <em>Big Data &amp; Society</em>, <em>8</em>(1), 16. <a href="https://doi.org/10.1177/2053951721996046">https://doi.org/10.1177/2053951721996046</a>
</div>
<div id="ref-cottom2017lower" class="csl-entry" role="listitem">
Cottom, T. M. (2017). <em>Lower ed: <span>The</span> troubling rise of for-profit colleges in the new economy</em>. The New Press.
</div>
<div id="ref-RN4774" class="csl-entry" role="listitem">
Cottom, T. M. (2020). Where platform capitalism and racial capitalism meet: The sociology of race and racism in the digital society. <em>Sociology of Race and Ethnicity</em>, <em>6</em>(4), 441–449. <a href="https://doi.org/10.1177/2332649220949473">https://doi.org/10.1177/2332649220949473</a>
</div>
<div id="ref-dache2018dangling" class="csl-entry" role="listitem">
Dache-Gerbino, A., Kiyama, J. M., &amp; Sapp, V. T. (2018). The dangling carrot: <span>Proprietary</span> institutions and the mirage of college choice for <span>Latina</span> students. <em>The Review of Higher Education</em>, <em>42</em>(1), 29–60. <a href="https://doi.org/10.1353/rhe.2018.0033">https://doi.org/10.1353/rhe.2018.0033</a>
</div>
<div id="ref-RN4873" class="csl-entry" role="listitem">
Domina, T., Penner, A., &amp; Penner, E. (2017). Categorical inequality: Schools as sorting machines. <em>Annual Review of Sociology</em>, <em>43</em>, 311–330. <a href="https://doi.org/10.1146/annurev-soc-060116-053354">https://doi.org/10.1146/annurev-soc-060116-053354</a>
</div>
<div id="ref-eabcomm" class="csl-entry" role="listitem">
EAB. (n.d.). <em>EAB: Managing school communication during COVID-19</em>. Retrieved from <a href="https://www.vistaequitypartners.com/spotlight/eab-school-communication-covid19/">https://www.vistaequitypartners.com/spotlight/eab-school-communication-covid19/</a>
</div>
<div id="ref-RN4728" class="csl-entry" role="listitem">
EAB. (2018). <em>Making your digital ads count: 15 lessons on new and emerging techniques in undergraduate recruitment marketing</em>. <span>EAB</span>.
</div>
<div id="ref-RN2004" class="csl-entry" role="listitem">
EAB. (2019). The 5 key stages of college enrollment—and which metrics to track during each. Retrieved from <a href="https://eab.com/insights/daily-briefing/enrollment/the-5-key-stages-of-college-enrollment-and-which-metrics-to-track-during-each/">https://eab.com/insights/daily-briefing/enrollment/the-5-key-stages-of-college-enrollment-and-which-metrics-to-track-during-each/</a>
</div>
<div id="ref-RN2356" class="csl-entry" role="listitem">
Espeland, W. N., &amp; Sauder, M. L. (2007). Rankings and reactivity: How public measures recreate social worlds. <em>American Journal of Sociology</em>, <em>113</em>(1), 1–40. Retrieved from <a href="<Go to ISI>://000248485000001">&lt;Go to ISI&gt;://000248485000001</a>
</div>
<div id="ref-RN5003" class="csl-entry" role="listitem">
Espeland, W. N., &amp; Sauder, M. L. (2016). <em>Engines of anxiety: Academic rankings, reputation, and accountability</em> (pp. xii, 281 pages). New York, New York: Russell Sage Foundation.
</div>
<div id="ref-RN5007" class="csl-entry" role="listitem">
Espeland, W. N., &amp; Stephens, M. L. (2008). A sociology of quantification. <em>Archives Europeennes De Sociologie</em>, <em>49</em>(3), 397–432. Retrieved from <a href="<Go to ISI>://WOS:000265147000002">&lt;Go to ISI&gt;://WOS:000265147000002</a>
</div>
<div id="ref-RN4810" class="csl-entry" role="listitem">
Fourcade, M., &amp; Healy, K. (2013). Classification situations: Life-chances in the neoliberal era. <em>Accounting Organizations and Society</em>, <em>38</em>(8), 559–572. Journal Article. <a href="https://doi.org/10.1016/j.aos.2013.11.002">https://doi.org/10.1016/j.aos.2013.11.002</a>
</div>
<div id="ref-RN5015" class="csl-entry" role="listitem">
Fourcade, Marion, &amp; Healy, K. J. (2024). <em>The ordinal society</em> (pp. pages cm). Cambridge, Massachusetts ; London, England: Harvard University Press.
</div>
<div id="ref-RN4887" class="csl-entry" role="listitem">
Harcourt, B. E. (2007). <em>Against prediction: Profiling, policing, and punishing in an actuarial age</em>. Chicago: University of Chicago Press.
</div>
<div id="ref-RN4851" class="csl-entry" role="listitem">
Harcourt, B. E. (2015). Risk as a proxy for race: The dangers of risk assessment. <em>Federal Sentencing Reporter</em>, <em>27</em>(4), 237–243. <a href="https://doi.org/10.1525/fsr.2015.27.4.237">https://doi.org/10.1525/fsr.2015.27.4.237</a>
</div>
<div id="ref-RN4874" class="csl-entry" role="listitem">
Hirschman, D., Berrey, E., &amp; Rose-Greenland, F. (2016). Dequantifying diversity: Affirmative action and admissions at the university of michigan. <em>Theory and Society</em>, <em>45</em>(3), 265–301. <a href="https://doi.org/10.1007/s11186-016-9270-2">https://doi.org/10.1007/s11186-016-9270-2</a>
</div>
<div id="ref-RN4778" class="csl-entry" role="listitem">
Hirschman, D., &amp; Bosk, E. A. (2020). Standardizing biases: Selection devices and the quantification of race. <em>Sociology of Race and Ethnicity</em>, <em>6</em>(3), 348–364. <a href="https://doi.org/10.1177/2332649219844797">https://doi.org/10.1177/2332649219844797</a>
</div>
<div id="ref-RN4324" class="csl-entry" role="listitem">
Holland, M. M. (2019). <em>Divergent paths to college: Race, class, and inequality in high schools</em>. Rutgers University Press. <a href="https://doi.org/10.36019/9780813590288">https://doi.org/10.36019/9780813590288</a>
</div>
<div id="ref-RN2771" class="csl-entry" role="listitem">
Hossler, D., &amp; Bean, J. P. (1990). <em>The strategic management of college enrollments</em>. Jossey-Bass.
</div>
<div id="ref-RN2133" class="csl-entry" role="listitem">
Hoxby, C. M. (1997). <em>How the changing market structure of <span>U.S.</span> <span class="nocase">higher</span> education explains college tuition</em> (No. 6323). National Bureau of Economic Research. Retrieved from <a href="http://www.nber.org/papers/W6323.pdf">http://www.nber.org/papers/W6323.pdf</a>
</div>
<div id="ref-RN5014" class="csl-entry" role="listitem">
Jaquette, O., Han, C., &amp; Castañeda, I. (2024). The private school network: Recruiting visits to private high schools by public and private universities. <em>Research in Higher Education</em>. Journal Article. <a href="https://doi.org/10.1007/s11162-024-09783-w">https://doi.org/10.1007/s11162-024-09783-w</a>
</div>
<div id="ref-RN4330" class="csl-entry" role="listitem">
Jaquette, O., &amp; Salazar, K. (2018). Colleges recruit at richer, whiter high schools. Retrieved from <a href="https://www.nytimes.com/interactive/2018/04/13/opinion/college-recruitment-rich-white.html">https://www.nytimes.com/interactive/2018/04/13/opinion/college-recruitment-rich-white.html</a>
</div>
<div id="ref-RN5012" class="csl-entry" role="listitem">
Jaquette, O., &amp; Salazar, K. G. (2024). A sociological analysis of structural racism in <span>“student list”</span> lead generation products. <em>Educational Evaluation and Policy Analysis</em>, <em>46</em>(2), 276–308. <a href="https://doi.org/10.3102/01623737231210894">https://doi.org/10.3102/01623737231210894</a>
</div>
<div id="ref-list_biz" class="csl-entry" role="listitem">
Jaquette, O., Salazar, K. G., &amp; Martin, P. (2022). <em>The student list business: Primer and market dynamics</em>. <span>The Institute for College Access and Success</span>. Retrieved from <a href="https://ticas.org/wp-content/uploads/2022/09/The-Student-List-Business_-Primer-and-Market-Dynamics.pdf">https://ticas.org/wp-content/uploads/2022/09/The-Student-List-Business_-Primer-and-Market-Dynamics.pdf</a>
</div>
<div id="ref-RN4407" class="csl-entry" role="listitem">
Khan, S. R. (2011). <em>Privilege: The making of an adolescent elite at <span class="nocase">St. Paul’s School</span></em>. Princeton, N.J.: Princeton University Press.
</div>
<div id="ref-RN3522" class="csl-entry" role="listitem">
Killgore, L. (2009). Merit and competition in selective college admissions. <em>Review of Higher Education</em>, <em>32</em>(4), 469–488. <a href="https://doi.org/10.1353/rhe.0.0083">https://doi.org/10.1353/rhe.0.0083</a>
</div>
<div id="ref-RN4779" class="csl-entry" role="listitem">
Korver-Glenn, E. (2022). <em>Race brokers: Housing markets and racial segregation in 21st <span class="nocase">c</span>entury urban <span>A</span>merica</em>. New York, NY: Oxford University Press.
</div>
<div id="ref-RN4989" class="csl-entry" role="listitem">
Kosinski, M., Stillwell, D., &amp; Graepel, T. (2013). Private traits and attributes are predictable from digital records of human behavior. <em>Proc Natl Acad Sci U S A</em>, <em>110</em>(15), 5802–5805. <a href="https://doi.org/10.1073/pnas.1218772110">https://doi.org/10.1073/pnas.1218772110</a>
</div>
<div id="ref-RN2406" class="csl-entry" role="listitem">
Kraatz, M. S., Ventresca, M. J., &amp; Deng, L. N. (2010). Precarious values and mundane innovations: Enrollment management in american liberal arts colleges. <em>Academy of Management Journal</em>, <em>53</em>(6), 1521–1545. <a href="https://doi.org/10.5465/amj.2010.57319260">https://doi.org/10.5465/amj.2010.57319260</a>
</div>
<div id="ref-RN4884" class="csl-entry" role="listitem">
Kraus, M. W., Onyeador, I. N., Daumeyer, N. M., Rucker, J. M., &amp; Richeson, J. A. (2019). The misperception of racial economic inequality. <em>Perspectives on Psychological Science</em>, <em>14</em>(6), 899–921. <a href="https://doi.org/10.1177/1745691619863049">https://doi.org/10.1177/1745691619863049</a>
</div>
<div id="ref-RN4986" class="csl-entry" role="listitem">
Litten, L. H., Sullivan, D. J., &amp; Brodigan, D. L. (1983). <em>Applying market research in college admissions</em> (pp. xxii, 303 p.). New York: College Entrance Examination Board.
</div>
<div id="ref-RN5005" class="csl-entry" role="listitem">
McArthur, D., &amp; Reeves, A. (2022). The unintended consequences of quantifying quality: Does ranking school performance shape the geographical concentration of advantage?&lt;SUP&gt;1&lt;/SUP&gt;. <em>American Journal of Sociology</em>, <em>128</em>(2), 515–551. <a href="https://doi.org/10.1086/722470">https://doi.org/10.1086/722470</a>
</div>
<div id="ref-RN1814" class="csl-entry" role="listitem">
McDonough, P. M. (1997). <em>Choosing colleges: How social class and schools structure opportunity</em> (pp. xi, 174 p.). Albany: State University of New York Press.
</div>
<div id="ref-RN4957" class="csl-entry" role="listitem">
McKelvey, F. (2022). When the new magic was new: The claritas corporation and the clustering of america. <em>Ieee Annals of the History of Computing</em>, <em>44</em>(4), 44–56. <a href="https://doi.org/10.1109/mahc.2022.3214223">https://doi.org/10.1109/mahc.2022.3214223</a>
</div>
<div id="ref-mcpherson2001birds" class="csl-entry" role="listitem">
McPherson, M., Smith-Lovin, L., &amp; Cook, J. M. (2001). Birds of a feather: <span>Homophily</span> in social networks. <em>Annual Review of Sociology</em>, <em>27</em>(1), 415–444.
</div>
<div id="ref-RN5008" class="csl-entry" role="listitem">
Mennicken, A., &amp; Espeland, W. N. (2019). What’s new with numbers? Sociological approaches to the study of quantification. <em>Annual Review of Sociology</em>, <em>45</em>, 223–245. <a href="https://doi.org/10.1146/annurev-soc-073117-041343">https://doi.org/10.1146/annurev-soc-073117-041343</a>
</div>
<div id="ref-RN5021" class="csl-entry" role="listitem">
Noel-Levitz. (1998). <em>National enrollment management survey: Findings for fall 1997 four-year institutions</em>. Noel-Levitz.
</div>
<div id="ref-RN4786" class="csl-entry" role="listitem">
Norris, D. (2021). Embedding racism: City government credit ratings and the institutionalization of race in markets. <em>Social Problems</em>. <a href="https://doi.org/10.1093/socpro/spab066">https://doi.org/10.1093/socpro/spab066</a>
</div>
<div id="ref-RN4881" class="csl-entry" role="listitem">
Norris, D. (2022). The illusion of transparency: The political double standard in city credit ratings. <em>Socio-Economic Review</em>. <a href="https://doi.org/10.1093/ser/mwac016">https://doi.org/10.1093/ser/mwac016</a>
</div>
<div id="ref-RN4849" class="csl-entry" role="listitem">
O’Neil, C. (2016). <em>Weapons of math destruction: How big data increases inequality and threatens democracy</em> (First edition.). New York: Crown.
</div>
<div id="ref-RN5017" class="csl-entry" role="listitem">
Oracle. (n.d.). <em>Loading and assigning EPS market codes</em>. Oracle. Retrieved from <a href="https://docs.oracle.com/cd/E29376_01/hrcs90r5/eng/psbooks/lsad/chapter.htm?File=lsad/htm/lsad40.htm">https://docs.oracle.com/cd/E29376_01/hrcs90r5/eng/psbooks/lsad/chapter.htm?File=lsad/htm/lsad40.htm</a>
</div>
<div id="ref-RN4877" class="csl-entry" role="listitem">
Poon, M. (2007). Scorecards as devices for consumer credit: The case of <span>Fair, Isaac &amp; Company Incorporated</span>. <em>Sociological Review</em>, <em>55</em>, 284–306. <a href="https://doi.org/10.1111/j.1467-954X.2007.00740.x">https://doi.org/10.1111/j.1467-954X.2007.00740.x</a>
</div>
<div id="ref-poon2022rethinking" class="csl-entry" role="listitem">
Poon, O. Y. A., &amp; Bastedo, M. N. (2022). <em>Rethinking college admissions: Research-based practice and policy</em>. Harvard Education Press. Retrieved from <a href="https://books.google.com/books?id=IjehEAAAQBAJ">https://books.google.com/books?id=IjehEAAAQBAJ</a>
</div>
<div id="ref-RN4520" class="csl-entry" role="listitem">
Posecznick, A. (2017). <em>Selling hope and college: Merit, markets, and recruitment in an unranked school</em>. Ithaca, NY: Cornell University Press.
</div>
<div id="ref-RN4131" class="csl-entry" role="listitem">
Posselt, J. R. (2016). <em>Inside graduate admissions: Merit, diversity, and faculty gatekeeping</em>. Cambridge, MA: Harvard University Press.
</div>
<div id="ref-rothstein2017color" class="csl-entry" role="listitem">
Rothstein, R. (2017). <em>The color of law: <span>A</span> forgotten history of how our government segregated <span>America</span></em>. Liveright Publishing.
</div>
<div id="ref-RN4741" class="csl-entry" role="listitem">
Ruffalo Noel Levitz. (2020). <em>2020 marketing and recruitment practices for undergraduate students report</em>. <span>Ruffalo Noel Levitz</span>. Retrieved from <a href="https://learn.ruffalonl.com/rs/395-EOG-977/images/2020_Marketing_Recruitment%20Practices_Undergraduate_Students.pdf">https://learn.ruffalonl.com/rs/395-EOG-977/images/2020_Marketing_Recruitment%20Practices_Undergraduate_Students.pdf</a>
</div>
<div id="ref-rnlabout" class="csl-entry" role="listitem">
Ruffalo Noel Levitz. (2023). <em>About RNL</em>. Retrieved from <a href="https://www.ruffalonl.com/about-ruffalo-noel-levitz/">https://www.ruffalonl.com/about-ruffalo-noel-levitz/</a>
</div>
<div id="ref-RN4895" class="csl-entry" role="listitem">
Ruffalo Noel-Levitz. (2022). <em>2022 marketing and recruitment practices for undergraduate students report</em>. Ruffalo Noel-Levitz. Retrieved from <a href="https://www.ruffalonl.com/papers-research-higher-education-fundraising/marketing-and-recruitment-practices-for-undergraduate-students/">https://www.ruffalonl.com/papers-research-higher-education-fundraising/marketing-and-recruitment-practices-for-undergraduate-students/</a>
</div>
<div id="ref-RN4759" class="csl-entry" role="listitem">
Salazar, K. G. (2022). Recruitment redlining by public research universities in the los angeles and dallas metropolitan areas. <em>The Journal of Higher Education</em>, <em>93</em>, 585–621. <a href="https://doi.org/10.1080/00221546.2021.2004811">https://doi.org/10.1080/00221546.2021.2004811</a>
</div>
<div id="ref-RN4758" class="csl-entry" role="listitem">
Salazar, K. G., Jaquette, O., &amp; Han, C. (2021). Coming soon to a neighborhood near you? Off-campus recruiting by public research universities. <em>American Educational Research Journal</em>, <em>58</em>(6), 1270–1314. <a href="https://doi.org/10.3102/00028312211001810">https://doi.org/10.3102/00028312211001810</a>
</div>
<div id="ref-RN2376" class="csl-entry" role="listitem">
Sauder, M. L. (2008). Interlopers and field change: The entry of US news into the field of legal education. <em>Administrative Science Quarterly</em>, <em>53</em>(2), 209–234. Journal Article. Retrieved from <a href="<Go to ISI>://000258783000001">&lt;Go to ISI&gt;://000258783000001</a>
</div>
<div id="ref-RN2375" class="csl-entry" role="listitem">
Sauder, M. L., &amp; Espeland, W. N. (2009). The discipline of rankings: Tight coupling and organizational change. <em>American Sociological Review</em>, <em>74</em>(1), 63–82. Journal Article. Retrieved from <a href="<Go to ISI>://000263490200004">&lt;Go to ISI&gt;://000263490200004</a>
</div>
<div id="ref-RN4738" class="csl-entry" role="listitem">
Scott, W. R., &amp; Davis, G. F. (2007). The dyadic environment of the organization. In W. R. Scott &amp; G. F. Davis (Eds.), <em>Organizations and organizing: <span>Rational</span>, natural, and open systems perspectives</em> (pp. 220–244). Upper Saddle River, New Jersey: Pearson, Prentice Hall.
</div>
<div id="ref-RN1273" class="csl-entry" role="listitem">
Sewell, W. H., &amp; Shah, V. P. (1967). Socioeconomic status, intelligence, and attainment of higher education. <em>Sociology of Education</em>, <em>40</em>(1), 1–23. Retrieved from <a href="<Go to ISI>://A1967ZD96500001 ">&lt;Go to ISI&gt;://A1967ZD96500001 </a>
</div>
<div id="ref-RN3519" class="csl-entry" role="listitem">
Stevens, M. L. (2007). <em>Creating a class: <span>College</span> admissions and the education of elites</em>. Cambridge, MA: Harvard University Press.
</div>
<div id="ref-RN2377" class="csl-entry" role="listitem">
Stevens, M. L., Armstrong, E. A., &amp; Arum, R. (2008). Sieve, incubator, temple, hub: Empirical and theoretical advances in the sociology of higher education. <em>Annual Review of Sociology</em>, <em>34</em>, 127–151. <a href="https://doi.org/10.1146/annurev.soc.34.040507.134737">https://doi.org/10.1146/annurev.soc.34.040507.134737</a>
</div>
<div id="ref-RN4517" class="csl-entry" role="listitem">
Stevens, M. L., &amp; Gebre-Medhin, B. (2016). Association, service, market: Higher education in american political development. <em>Annual Review of Sociology</em>, <em>42</em>, 121–142. <a href="https://doi.org/10.1146/annurev-soc-081715-074240">https://doi.org/10.1146/annurev-soc-081715-074240</a>
</div>
<div id="ref-RN4980" class="csl-entry" role="listitem">
Takamiya, T. (2005). <em>Mechanisms for marketing higher education information services: The case of the college board</em>. University of Pennsylvania.
</div>
<div id="ref-RN4993" class="csl-entry" role="listitem">
Taylor, B. J., Rosinger, K., &amp; Ford, K. S. (2024). The shape of the sieve: Which components of the admissions application matter most in particular institutional contexts? <em>Sociology of Education</em>. <a href="https://doi.org/10.1177/00380407241230007">https://doi.org/10.1177/00380407241230007</a>
</div>
<div id="ref-RN4004" class="csl-entry" role="listitem">
Thornton, P. H. (2002). The rise of the corporation in a craft industry: Conflict and conformity in institutional logics. <em>Academy of Management Journal</em>, <em>45</em>(1), 81–101. <a href="https://doi.org/10.2307/3069286">https://doi.org/10.2307/3069286</a>
</div>
<div id="ref-RN161" class="csl-entry" role="listitem">
Walsh, K. (1995). <em>Public services and market mechanisms: Competition, contracting and the new public management</em> (p. 284). Basingstoke, U.K.: Macmillan Press.
</div>
<div id="ref-RN1549" class="csl-entry" role="listitem">
Winston, G. C. (1999). Subsidies, hierarchy and peers: The awkward economics of higher education. <em>Journal of Economic Perspectives</em>, <em>13</em>(1), 13–36. <a href="https://doi.org/10.1257/jep.13.1.13">https://doi.org/10.1257/jep.13.1.13</a>
</div>
<div id="ref-RN4982" class="csl-entry" role="listitem">
Zemsky, R., &amp; Oedel, P. (1983). <em>The structure of college choice / robert zemsky, penney oedel</em>. New York: College Entrance Examination Board.
</div>
</div>
<!-- TABLES -->
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-em-funnel" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-em-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./../assets/images/enroll_funnelv2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:45.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-em-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The Enrollment Funnel
</figcaption>
</figure>
</div>
</div>
</div>
<!-- TABLES -->
<div class="cell">
<div id="tbl-market-segment-characteristics" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-market-segment-characteristics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Simplified market segment profile, Connecticut Market 3: Fairfield County
</figcaption>
<div aria-describedby="tbl-market-segment-characteristics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Characteristic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Local</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">In-state</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Regional</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">National</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total test takers</td>
<td style="text-align: right;">550.0</td>
<td style="text-align: right;">1199.0</td>
<td style="text-align: right;">1664.0</td>
<td style="text-align: right;">3766.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Avg SAT (verbal + math)</td>
<td style="text-align: right;">770.0</td>
<td style="text-align: right;">850.0</td>
<td style="text-align: right;">970.0</td>
<td style="text-align: right;">980.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Avg # scores sent per test taker</td>
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">5.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Percent in top 20% of HS class</td>
<td style="text-align: right;">27.8</td>
<td style="text-align: right;">26.1</td>
<td style="text-align: right;">44.7</td>
<td style="text-align: right;">45.7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Percent aspiring to more than BA</td>
<td style="text-align: right;">30.6</td>
<td style="text-align: right;">41.5</td>
<td style="text-align: right;">54.5</td>
<td style="text-align: right;">62.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Percent family income more than $35,000</td>
<td style="text-align: right;">11.2</td>
<td style="text-align: right;">20.6</td>
<td style="text-align: right;">41.9</td>
<td style="text-align: right;">43.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Percent both parents with BA</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">16.3</td>
<td style="text-align: right;">34.0</td>
<td style="text-align: right;">37.1</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-sample-institutional-profile" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sample-institutional-profile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Simplified sample institutional profile for anonymous institution, students from Connecticut Market 3: Fairfield County
</figcaption>
<div aria-describedby="tbl-sample-institutional-profile-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Local</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">In-state</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Regional</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">National</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total number of scores received</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">58.0</td>
<td style="text-align: right;">69.0</td>
<td style="text-align: right;">109.0</td>
<td style="text-align: right;">237.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pct of all test-takers in segment</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">4.8</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">2.9</td>
<td style="text-align: right;">3.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lib_arts_num</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">25.0</td>
<td style="text-align: right;">35.0</td>
<td style="text-align: right;">61.0</td>
<td style="text-align: right;">121.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">lib_arts_share</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">8.4</td>
<td style="text-align: right;">7.0</td>
<td style="text-align: right;">5.3</td>
<td style="text-align: right;">5.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">engineering_num</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">10.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">engineering_share</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">5.8</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">1.8</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-market-segment-institutions" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-market-segment-institutions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Top 5 institutions in terms of number of scores sent by segment, Connecticut Market 3: Fairfield County
</figcaption>
<div aria-describedby="tbl-market-segment-institutions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Local (N=550)
</div></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
In-state (N=1,199)
</div></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Regional (N=1,664)
</div></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
National (N=3,766)
</div></th>
</tr>
<tr class="odd">
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Num</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pct</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Num</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pct</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Num</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pct</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Num</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pct</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">277</td>
<td style="text-align: right;">50.4</td>
<td style="text-align: left;">priv ma</td>
<td style="text-align: right;">757</td>
<td style="text-align: right;">63.1</td>
<td style="text-align: left;">pub doct</td>
<td style="text-align: right;">610</td>
<td style="text-align: right;">36.7</td>
<td style="text-align: left;">pub doct</td>
<td style="text-align: right;">1226</td>
<td style="text-align: right;">32.6</td>
<td style="text-align: left;">pub doc</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">261</td>
<td style="text-align: right;">47.5</td>
<td style="text-align: left;">priv ma</td>
<td style="text-align: right;">515</td>
<td style="text-align: right;">43.0</td>
<td style="text-align: left;">pub ma</td>
<td style="text-align: right;">348</td>
<td style="text-align: right;">20.9</td>
<td style="text-align: left;">priv doct</td>
<td style="text-align: right;">371</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: left;">priv doct</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">33.3</td>
<td style="text-align: left;">priv ma</td>
<td style="text-align: right;">438</td>
<td style="text-align: right;">36.5</td>
<td style="text-align: left;">pub ma</td>
<td style="text-align: right;">272</td>
<td style="text-align: right;">16.3</td>
<td style="text-align: left;">priv doct</td>
<td style="text-align: right;">327</td>
<td style="text-align: right;">8.7</td>
<td style="text-align: left;">priv res</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">18.7</td>
<td style="text-align: left;">pub doct</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">15.3</td>
<td style="text-align: left;">pub ma</td>
<td style="text-align: right;">248</td>
<td style="text-align: right;">14.9</td>
<td style="text-align: left;">pub doct</td>
<td style="text-align: right;">312</td>
<td style="text-align: right;">8.3</td>
<td style="text-align: left;">priv doct</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">18.2</td>
<td style="text-align: left;">pub ma</td>
<td style="text-align: right;">177</td>
<td style="text-align: right;">14.8</td>
<td style="text-align: left;">pub ma</td>
<td style="text-align: right;">197</td>
<td style="text-align: right;">11.8</td>
<td style="text-align: left;">pub doct</td>
<td style="text-align: right;">308</td>
<td style="text-align: right;">8.2</td>
<td style="text-align: left;">priv doct</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><span class="citation" data-cites="RN3519">Stevens (<a href="#ref-RN3519" role="doc-biblioref">2007</a>)</span> describes the archives of annual reports of admissions activities from a selective liberal arts college. In the 1942 report, “Section 2.5 is titled ’Secondary School Quartile Standings,” a measure of where matriculants fell in the rankings of their high school classes” <span class="citation" data-cites="RN3519">(<a href="#ref-RN3519" role="doc-biblioref">Stevens, 2007</a>)</span> while Section 3.11 describes the high schools visited. In the chapter entitled “Travel,” <span class="citation" data-cites="RN3519">Stevens (<a href="#ref-RN3519" role="doc-biblioref">2007, p. 69</a>)</span> describes how The College used record-keeping to inform decisions about visits to local high schools in the 2000s: “The College keeps files on hundreds of schools across the country, and around the globe, with which it had contact The files enable officers to quickly discern”how we’ve done here lately,” with the number, relative quality, and yield rate of applicants from a particular school.”<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Thus, <span class="citation" data-cites="RN4975">Chun (<a href="#ref-RN4975" role="doc-biblioref">2021, p. 82</a>)</span> writes, “echo chambers are not unfortunate errors, but deliberate goals” because “homophily is used to create agitated clusters of individuals whose angry similarity and overwhelming attrication to their common object of hatred both repel them from one another and glue them together.”<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>say that Pennsylvania Department of Education was also a partner; see page x of Zemsky<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><a href="#tbl-market-segment-institutions" class="quarto-xref">Table&nbsp;3</a> recreates the top panel of <span class="citation" data-cites="RN4982">Zemsky &amp; Oedel (<a href="#ref-RN4982" role="doc-biblioref">1983, fig. 2.1</a>)</span> for the Fairfield County, CT local market. For example, of the 550 local students, 277 (50.4%) sent scores to institution #1, which was a private master’s granting institution. Of the 1,199 in-state students, 757 (63.1) sent scores to institution #1, a public doctoral granting institution, and 515 (43.0%) sent scores to institution #2, a public master’s granting institution.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><span class="citation" data-cites="RN5016">Board (<a href="#ref-RN5016" role="doc-biblioref">n.d.</a>)</span> states that “geomarkets are areas within a state that represent a further segmentation of a population. Students from California don’t all share the same college-going behaviors. We have accounted for this variance by segmenting the 50 states into 304 geomarkets to provide further insight into student behaviors within particular areas of individual states.”<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>We can think of students sending SAT scores to colleges as a “two-mode” social network in which students (mode 1) send SAT scores – the network tie – to colleges (mode 2). Next, the authors develop “Tinker Toy” diagrams that show which institutions are connected to one another. These diagrams are drawn separately for each student segment – local, in-state, regional, and national – and separately for each geomarket, such that the analyses convey which institutions compete with one another for which student segments in each local market.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>For example, describing the Figure 4.4 “Structure of Fairfield County Regional Market,” <span class="citation" data-cites="RN4982">(<a href="#ref-RN4982" role="doc-biblioref">Zemsky &amp; Oedel, 1983, p. 54</a>)</span> state that “competitive overlap, moreover, is often confined to institutions belonging to the same [Carnegie] type as well sector. For example, public flagships compete primarily with other public flagships; private standard colleges, with other private standard colleges; Catholic institutions, with other Catholic institutions.”<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>